### ISSUE TITLE
Implement transaction fee refunds

### ISSUE THREAD

**Issue by austinabell** [cosmos/ethermint#125]
Currently in Cosmos, there are no refunds and no framework set up for refunding unused gas, but for consistency this should be done in the evm state transition. Unfortunately since the full fees/ gas cost is paid out to validators in the ante handler, this needs to be somehow retrieved back and refunded to the transaction sender. Will explore this later, but it may be out of scope for now and not necessary

**Comment by fedekunze** [comment]
@austinabell I noticed that gas is consumed twice at the ante handler and then right after the state transition. Why is that the case?

**Comment by austinabell** [comment]
> @austinabell I noticed that gas is consumed twice at the ante handler and then right after the state transition. Why is that the case?

The first is the signature verification consumption (ante handler) and the second is charging gas for the computation (and I guess estimated storage costs) performed in the state transition. In Ethereum, this happens all in one pass, but since the signature verification happens in the ante handler in Cosmos, the gas charging needs to be separated.

If you only support transactions from the web3 API, then you could charge gas all in the state transition phase, but support for Cosmos std-txs and being able to use EVM as a module is important.
