### ISSUE TITLE
Prevent non-numeric chain id within emintd

### ISSUE THREAD

**Issue by okwme** [cosmos/ethermint#138]
__System info:__ 
current master: fc57cabcab98a175cf67e9def35fc22f8e25348a
__Steps to reproduce:__

1. Follow all steps from https://github.com/ChainSafe/ethermint-deploy
2. Except use a non-numeric chain id in step 3
3. Run `emintcli rest-server --laddr "tcp://localhost:8545"`
4. Receive very helpful error: `panic: Invalid chainID: [non-integer-chain-id], must be integer format`

__Expected behavior:__
Should have been blocked adding a non-numeric chain id in step 3

**Comment by austinabell** [comment]
can't request a review but let me know if #140 is sufficient. One other thing I could add is setting the chain-id to a random integer if unset, but I think it may be counterproductive since the chain-id is functionally relevant in Ethermint
