### ISSUE TITLE
Make it easier to use with metamask

### ISSUE THREAD

**Issue by okwme** [cosmos/ethermint#145]
__Proposal:__ Show private key as part of key generation to make it easier

__Current behavior:__ Prints a mnemonic phrase with 256 bits of entropy, this results in a 24 word long mnemonic phrase which metamask can not import. This means that your ethermint account can't be used with metamask, one of the most popular web3 interfaces.

__Desired behavior:__ Either allow a 12 word mnemonic phrase (issue filed with SDK [here](https://github.com/cosmos/cosmos-sdk/issues/4278#issuecomment-549070624)) or print the private key that can be imported by Metamask

__Use case:__ Mimics traditional evm developer user flow to make working with ethermint same as working with ethereum

Requests may be closed if we're not actively planning to work on them.

**Comment by austinabell** [comment]
Yeah metamask seems to be the last dev tooling that is not fully supported and this would be pretty essential. Thanks for documenting this issue

Am working on a solution and trying to migrate keybase back to Cosmos keybase to allow for all other functionality including exporting the private key, which should be sufficient for Metamask, and if the 12 word mnemonic was implemented in Cosmos it would be available to use in Ethermint as well.

Edit: actually the export may not be sufficient if the current functionality requires to encode the private key, but workarounds can be done to ensure usability with metamask

**Comment by vaibhavchellani** [comment]
I think this can be closed @austinabell

**Comment by austinabell** [comment]
> I think this can be closed @austinabell

Was just keeping open to track the 12 word mnemonic issue in Cosmos, but yeah will close because it is irrelevant to Ethermint, thanks
