### ISSUE TITLE
enable CORS options

### ISSUE THREAD

**Issue by okwme** [cosmos/ethermint#148]
__System info:__ 021c9f440a7c3355f4fbae44a143de30ea3473d6

__Steps to reproduce:__

1. Open browser
2. In console try to query ethermint with the following `fetch` query:
```js
fetch("http://localhost:8545/", {
  "method": "POST",
  "headers": {
    "content-type": "application/json"
  },
  "body": {
    "jsonrpc": "2.0",
    "method": "eth_accounts",
    "params": [],
    "id": 1
  }
})
.then(response => {
  console.log(response);
})
.catch(err => {
  console.log(err);
});
```
3. See CORS error.

_Alternatively_
1. Go to [remix](https://remix.ethereum.org/#optimize=false&evmVersion=null&version=soljson-v0.5.11+commit.c082d0b4.js)
2. click the deploy tab
3. select "Environment" > "Web3Provider" and use `http://localhost:8545`
4. see error in console about CORS

__Expected behavior:__ Be able to connect to a web3 endpoint with CORS headers set

__Actual behavior:__ CORS headers not set

__Additional info:__ There's a long history debating whether or not the REST servers in the Cosmos-SDK should allow CORS to be set or not ([link](https://github.com/cosmos/cosmos-sdk/issues?utf8=%E2%9C%93&q=CORS)). I'm of the opinion that they should be configurable and up to the user to make their own security assumptions, but the going method is to expect a proxy server to be used to configure headers. This is the better solution for production but for testing it makes things much easier for web devs if they can just use the endopint directly instead of having to run multiple servers.

If the goal of Ethermint is to mimic current popular web3 endpoints like Geth, then being able to include options like `--rpccorsdomain` should be considered for inclusion.

**Comment by austinabell** [comment]
I agree completely there should be a flag to enable cors for the server. If anyone needs to use remix for the time being, you can use a reverse-proxy to set the headers and Remix works fine.

Adding this functionality is something we explored very briefly but was put on hold for now.

**Comment by fedekunze** [comment]
closing as SDK 0.39.1 will come with the CORS options
