### ISSUE TITLE
Inconsistent evm time

### ISSUE THREAD

**Issue by HaoyangLiu** [cosmos/ethermint#166]
https://github.com/ChainSafe/ethermint/blob/b98685c46bbbb5bdd0c12f3003c2841903e57b1f/x/evm/types/state_transition.go#L74

The evm time should be derived from block header time. `time.Now().Unix()` will generate inconsistent value for different nodes.

**Comment by austinabell** [comment]
> https://github.com/ChainSafe/ethermint/blob/b98685c46bbbb5bdd0c12f3003c2841903e57b1f/x/evm/types/state_transition.go#L74
> 
> The evm time should be derived from block header time. `time.Now().Unix()` will generate inconsistent value for different nodes.

ahh yes good catch, I was going to come back to this but forgot since it didn't matter in any usages so far. I'll fix now and open a PR, do you have a way to test this with your own usage (I assume that arose this issue) or would you like me to find a way to test it in a contract in the future?

**Comment by HaoyangLiu** [comment]
I just read the code and find the issue. 

https://solidity.readthedocs.io/en/v0.4.24/units-and-global-variables.html?highlight=block.timestamp
If your solidity contract try to read `block.timestamp` and save it, then the inconsistent issue might arise.

**Comment by austinabell** [comment]
I'll look more in depth later, thanks for bringing up !
