### ISSUE TITLE
Update eth_accounts for workaround with keyring

### ISSUE THREAD

**Issue by austinabell** [cosmos/ethermint#169]
Ever since the keybase in Cosmos was updated to use the keyring, there requires a prompt to even view the keyring data. This was not a problem before as there was no prompt to query the keys in a file db. Now that this is changed, either the accounts should be cached so the prompt is only required once and if the keyring requires a prompt it will just return the cached data or there needs to be another workaround to get this data available by a query.

Code for `eth_accounts`: https://github.com/ChainSafe/ethermint/blob/development/rpc/eth_api.go#L107

**Comment by fedekunze** [comment]
I think this issue is not valid anymore?

**Comment by austinabell** [comment]
> I think this issue is not valid anymore?

does the prompt not happen now when not using dev keys with updated sdk version? Feel free to close if you'd like anyway

**Comment by fedekunze** [comment]
it doesn't prompt for pwd 👍
