### ISSUE TITLE
AddGenesisAccountCmd doesn't honor passed config

### ISSUE THREAD

**Issue by okwme** [cosmos/ethermint#171]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
c99d5cf6c5ca0b4e667fc55d72292b5eef04a7b2
__Steps to reproduce:__

1. set up external app that imports ethermint module
2. rename cmd and config files to someting else besides `emint` (i'm using `exmint`)
3. init chain with `exmintd init mymoniker --chain-id 8`
4. add keys like `exmintcli keys add mykey`
5. add a genesis account like `exmintd add-genesis-account $(exmintcli keys show mykey -a) 1000000000000000000photon,1000000000000000000stake`
and get the error:
```
ERROR: failed to unmarshal genesis state: /home/billy/.emintd/config/genesis.json does not exist, run `init` first
```
cause it's looking in `.emintd` instead of `.exmintd`.  

Can be fixed by using flag `--home` like:
```
exmintd add-genesis-account $(exmintcli keys show mykey -a) 1000000000000000000photon,1000000000000000000stake --home ~/.exmintd
```

When checking the `/client/genaccounts/main.go` file where `AddGenesisAccountCmd` is defined it looks for the home flag but ignores the `defaultClientHome` that is passed as a parameter https://github.com/ChainSafe/ethermint/blob/development/client/genaccounts/main.go#L47

__Expected behavior:__ Use my custom config directory

__Actual behavior:__ Used the config directory for ethermint source

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by austinabell** [comment]
related #159 but I will look into that flag that is being ignored in genaccounts, it's probably just the flag not being enabled through the CLI (I hadn't tried to override the home directory with that flag before)
