### ISSUE TITLE
cannot get transaction receipt for contract deployments

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#261]
__System info:__ branch: development

__Steps to reproduce:__

1. send some transaction, wait for it to be included, eg:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params":[{"data":"0x60806040526000805534801561001457600080fd5b5060d2806100236000396000f3fe6080604052348015600f57600080fd5b5060043610603c5760003560e01c80634f2be91f1460415780636deebae31460495780638ada066e146051575b600080fd5b6047606d565b005b604f6080565b005b60576094565b6040518082815260200191505060405180910390f35b6000808154809291906001019190505550565b600080815480929190600190039190505550565b6000805490509056fea265627a7a723158207b1aaa18c3100d8aa67f26a53f3cb83d2c69342d17327bd11e1b17c248957bfa64736f6c634300050c0032","from":"0xfe33d0a3efb35ab26fcbfb102e1663e068867ef1"}],"id":1}' -H "Content-Type: application/json" http://localhost:8545
```

2. try to get tx receipt (replace hash with tx hash returned in step 1)
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getTransactionReceipt","params":["0xcebbb6c7d109dcfa43983b776519194e02aa366dc4384164a12e85f578241b8b"],"id":1}' -H "Content-Type: application/json" http://localhost:8545``
```

3. error returned:
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"UnmarshalBinaryLengthPrefixed cannot decode empty bytes"}}
```

__Expected behavior:__ [What you expected to happen]
expected to retrieve transaction receipt

__Actual behavior:__ [What actually happened]

```{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"UnmarshalBinaryLengthPrefixed cannot decode empty bytes"}}

```

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
I'll start writing unit and integration tests for this on the EVM module first.

**Comment by fedekunze** [comment]
Ok, so I noted that there are 2 different methods that we are using. My question is, why are we using different keys to store the same object twice?

```go
// SetTransactionLogs sets the transaction's logs in the KVStore
func (k *Keeper) SetTransactionLogs(ctx sdk.Context, logs []*ethtypes.Log, hash []byte) error {
	store := ctx.KVStore(k.blockKey)
	encLogs, err := types.EncodeLogs(logs)
	if err != nil {
		return err
	}

	store.Set(types.LogsKey(hash), encLogs)
	return nil
}
```

and 

```go
// SetLogs sets the logs for a transaction in the KVStore.
func (csdb *CommitStateDB) SetLogs(hash ethcmn.Hash, logs []*ethtypes.Log) error {
	store := csdb.ctx.KVStore(csdb.storeKey)
	enc, err := EncodeLogs(logs)
	if err != nil {
		return err
	}

	if len(enc) == 0 {
		return nil
	}

	store.Set(LogsKey(hash[:]), enc)
	return nil
}
```

**Comment by fedekunze** [comment]
@austinabell do you know why is this the case? ^

**Comment by austinabell** [comment]
> @austinabell do you know why is this the case? ^

Not sure, you added it in: https://github.com/ChainSafe/ethermint/commit/da9157e406177b0994542dbf6e2440b218ec95b9#diff-e92fd73a1bdc984b3efe0b01db1b3783R108
That seems to be a different issue to this though.

As for this issue, that transaction is not a contract deployment (it has a `to` address), I can look into what specifically is happening now though. The deployment scripts should fail if this is the case

**Comment by austinabell** [comment]
receipts broke in https://github.com/ChainSafe/ethermint/pull/252 

How have you guys tested changes with this broken? Probably a good case to increase coverage run in CI wrt this so this doesn't break in future?

Edit: let me be more specific, some transactions fail after that PR, which leads to not being able to query the receipts, I didn't check that specific case but the receipts could have broken somewhere else

**Comment by noot** [comment]
I think it was broken before #252, I was seeing this problem when I was doing the filter implementation. I'll go back and try to see where it broke.

also just to be clear, this is only broken for contract deployments (I'm using `TestEth_GetTransactionReceipt` inside tests/rpc to test this) it works fine for a regular transaction with a `to` field. 

I believe that the contract deployment is actually silently failing, but still returning status 1 for some reason. eg. if I add `fmt.Printf("%v\n", tx.TxResult)` after the `txData := tx.TxResult.Data` line in rpc/eth_api.go,  I see `{1 [] failed to execute message; message index: 0: contract creation code storage out of gas  78724 68839 [] undefined {} [] 0}` which is of type https://godoc.org/github.com/tendermint/tendermint/abci/types#ResponseDeliverTx

so the contract deployment fails, but status/code is still 1.

**Comment by fedekunze** [comment]
So there are 2 bugs here that could have caused this issue:

1) It is possible that #252 may have increased the gas cost of txs, causing the contract creation to fail due to out of gas. 
2) Contract deployment incorrect status on failure, making it seem like it was successful but not returning any logs for receipts.

**Comment by noot** [comment]
I think case 1 is more likely, since the contract that's being deployed is small and shouldn't be running out of gas

**Comment by noot** [comment]
receipts worked on this commit: https://github.com/ChainSafe/ethermint/commit/1627ed81bf39a212a7ec63eeb8ead6e6bc58fc9d
 
they broke on this commit right after: https://github.com/ChainSafe/ethermint/commit/da9157e406177b0994542dbf6e2440b218ec95b9
