### ISSUE TITLE
cannot deploy contract with truffle

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#280]
__System info:__ development

__Steps to reproduce:__

The contract I was using to deploy was aragon's ENSFactory, specifically https://github.com/ChainSafe/aragonOS/blob/next/scripts/deploy-apm.js The deployment hangs at this line:
https://github.com/ChainSafe/aragonOS/blob/next/scripts/deploy-test-ens.js#L32

First I ran the ethermint daemon + rpc client. Then in aragonOS:
``` 
npm run compile
npx truffle exec --network localhost scripts/deploy-apm.js
```

I didn't try this with another contract, although I suspect it would also hang.

The contract deployment works fine with web3.

__Expected behavior:__ [What you expected to happen]
Contract would be deployed and script would continue

__Actual behavior:__ [What actually happened]
Script hanged at `await ENSFactory.new()`

**Comment by ayeteng** [comment]
Following truffle tutorial https://www.trufflesuite.com/tutorials/pet-shop but I cannot deploy contract with ethermint either.

**Comment by fedekunze** [comment]
@ayeteng just to confirm, which truffle version are you using?

**Comment by ayeteng** [comment]
Truffle v5.0.5

**Comment by noot** [comment]
to expand on the pet-shop issue:
```
$ truffle migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Migrations dry-run (simulation)
===============================
> Network name:    'development-fork'
> Network id:      8
> Block gas limit: 4294967295 (0xffffffff)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- Returned error: account cosmos1ckta7fd00vsm9gectglcd034em3zyek34lkf4l does not exist: unknown address.

    at /home/elizabeth/.nvm/versions/node/v10.12.0/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:364:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.24 (core: 5.1.24)
Node v10.12.0
```

this was with the `from` account set to the eth_accounts return address in truffle-config.js as well.

**Comment by noot** [comment]
closing this issue since the `npx truffle exec --network localhost scripts/deploy-apm.js` command now works inside aragonOS/
