### ISSUE TITLE
emintcli tx distribution withdraw-rewards runtime error

### ISSUE THREAD

**Issue by landoyjx** [cosmos/ethermint#283]
1. emintcli query staking validators
[
  {
    "operator_address": "cosmosvaloper1fx6zsgzed5y77hmlft32lv0dgt5ulp7utqkjva",
    "consensus_pubkey": "cosmosvalconspub1zcjduepqe9536ypt4lnyfe2vkck342w6j92d49r3kw2e9plr6yqnmuseer3qd2p9l8",
    "status": 3,
    "tokens": "100000000",
    "delegator_shares": "100000000.000000000000000000",
    "description": {
      "moniker": "mymoniker"
    },
    "unbonding_time": "1970-01-01T00:00:00Z",
    "commission": {
      "commission_rates": {
        "rate": "0.100000000000000000",
        "max_rate": "0.200000000000000000",
        "max_change_rate": "0.010000000000000000"
      },
      "update_time": "2020-05-07T00:35:02.064249Z"
    },
    "min_self_delegation": "1"
  }
]

2.  emintcli tx distribution withdraw-rewards cosmosvaloper1fx6zsgzed5y77hmlft32lv0dgt5ulp7utqkjva

panic: runtime error: invalid memory address or nil pointer dereference
[signal SIGSEGV: segmentation violation code=0x1 addr=0x38 pc=0x48ecde2]

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/auth/types.AccountRetriever.GetAccountWithHeight(0x0, 0x0, 0x52a70e0, 0xc000e5e100, 0x0, 0x0, 0x0, 0xc000e5e100, 0xc000edeac8, 0xc000e5e100, ...)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/auth/types/account_retriever.go:41 +0x62
github.com/cosmos/cosmos-sdk/x/auth/types.AccountRetriever.GetAccount(...)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/auth/types/account_retriever.go:33
github.com/cosmos/cosmos-sdk/x/auth/types.AccountRetriever.EnsureExists(0x0, 0x0, 0x52a70e0, 0xc000e5e100, 0x0, 0x0, 0x0, 0x10, 0x10)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/auth/types/account_retriever.go:61 +0x7a
github.com/cosmos/cosmos-sdk/x/auth/client.PrepareTxBuilder(0xc000e2f230, 0x52e1960, 0xc000d82a50, 0x0, 0x0, 0x30d40, 0x3ff0000000000000, 0x0, 0x5bc9eb8, 0x1, ...)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/auth/client/tx.go:305 +0x12c
github.com/cosmos/cosmos-sdk/x/auth/client.CompleteAndBroadcastTxCLI(0xc000e2f230, 0x52e1960, 0xc000d82a50, 0x0, 0x0, 0x30d40, 0x3ff0000000000000, 0x0, 0x5bc9eb8, 0x1, ...)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/auth/client/tx.go:60 +0x78
github.com/cosmos/cosmos-sdk/x/auth/client.GenerateOrBroadcastMsgs(0x0, 0x0, 0x0, 0x52e8dc0, 0xc000ee0000, 0x5bc9eb8, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/auth/client/tx.go:51 +0x15c
github.com/cosmos/cosmos-sdk/x/distribution/client/cli.GetCmdWithdrawRewards.func1(0xc000e0d080, 0xc000e2e730, 0x1, 0x1, 0x0, 0x0)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/distribution/client/cli/tx.go:122 +0x3ea
github.com/spf13/cobra.(*Command).execute(0xc000e0d080, 0xc000e2e700, 0x1, 0x1, 0xc000e0d080, 0xc000e2e700)
	/Users/lando/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc000d8a840, 0x44ae840, 0xc000d8a840, 0x4ef3b36)
	/Users/lando/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lando/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc000d8a840, 0x50ffed0, 0x2, 0xc000dc1c20)
	/Users/lando/go/pkg/mod/github.com/tendermint/tendermint@v0.33.3/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/lando/test/ethermint/cmd/emintcli/main.go:82 +0x620

**Comment by fedekunze** [comment]
I dug into the stack trace and this is what I found:

when you submit a transaction with CLI, `PrepareTxBuilder` creates a new `AccountRetriever` instance from the auth Codec. Since we use a different account type, we use usually set the auth's `Codec` to Ethermint's codec. We'd need for the SDK to accept a custom codec instead of the standard one


```
// PrepareTxBuilder populates a TxBuilder in preparation for the build of a Tx.
func PrepareTxBuilder(txBldr authtypes.TxBuilder, cliCtx context.CLIContext) (authtypes.TxBuilder, error) {
	from := cliCtx.GetFromAddress()

	accGetter := authtypes.NewAccountRetriever(Codec, cliCtx) // this should be the one from ethermint
... 
```
