### ISSUE TITLE
emintcli tx send a b 1000stake not deduct fee

### ISSUE THREAD

**Issue by landoyjx** [cosmos/ethermint#288]
1. download chainsafe/ethermint development branch
2. make build; ./init.sh
2. emintcli keys add mykey2
3. emintcli tx send mykey mykey2 1000stake
4. emintcli query bank balance,
mykey stake balance is deducted 1000stake,
mykey2 stake balance is 1000stake,
gas fee doest not work.

**Comment by landoyjx** [comment]
in step3
[
  {
    "denom": "photon",
    "amount": "1000000000000000000"
  },
  {
    "denom": "stake",
    "amount": "999999999900000000"
  }
]

step4 transaction
{
  "chain_id": "8",
  "account_number": "0",
  "sequence": "1",
  "fee": {
    "amount": [],
    "gas": "200000"
  },
  "msgs": [
    {
      "type": "cosmos-sdk/MsgSend",
      "value": {
        "from_address": "cosmos1x7f0aqgucrwkefkdz9de2ddm2lq59vydh2w6vc",
        "to_address": "cosmos19azqtluqt9ap2elfkv3eewe8nmmfuqpfeepw5n",
        "amount": [
          {
            "denom": "stake",
            "amount": "10000"
          }
        ]
      }
    }
  ],
  "memo": ""
}

in step5
mykey balances
[
  {
    "denom": "photon",
    "amount": "1000000000000000000"
  },
  {
    "denom": "stake",
    "amount": "999999999899990000"
  }
]

mykey2 balances
[
  {
    "denom": "stake",
    "amount": "10000"
  }
]


full transaction query result
{
  "height": "14",
  "txhash": "DC083C19176DD1A2E8FD0E4415B2CF3A2E79E1138F04CA11AB391D67FAAE56FC",
  "raw_log": "[{\"msg_index\":0,\"log\":\"\",\"events\":[{\"type\":\"message\",\"attributes\":[{\"key\":\"action\",\"value\":\"send\"},{\"key\":\"sender\",\"value\":\"cosmos1x7f0aqgucrwkefkdz9de2ddm2lq59vydh2w6vc\"},{\"key\":\"module\",\"value\":\"bank\"}]},{\"type\":\"transfer\",\"attributes\":[{\"key\":\"recipient\",\"value\":\"cosmos19azqtluqt9ap2elfkv3eewe8nmmfuqpfeepw5n\"},{\"key\":\"amount\",\"value\":\"10000stake\"}]}]}]",
  "logs": [
    {
      "msg_index": 0,
      "log": "",
      "events": [
        {
          "type": "message",
          "attributes": [
            {
              "key": "action",
              "value": "send"
            },
            {
              "key": "sender",
              "value": "cosmos1x7f0aqgucrwkefkdz9de2ddm2lq59vydh2w6vc"
            },
            {
              "key": "module",
              "value": "bank"
            }
          ]
        },
        {
          "type": "transfer",
          "attributes": [
            {
              "key": "recipient",
              "value": "cosmos19azqtluqt9ap2elfkv3eewe8nmmfuqpfeepw5n"
            },
            {
              "key": "amount",
              "value": "10000stake"
            }
          ]
        }
      ]
    }
  ],
  "gas_wanted": "200000",
  "gas_used": "74185",
  "tx": {
    "type": "cosmos-sdk/StdTx",
    "value": {
      "msg": [
        {
          "type": "cosmos-sdk/MsgSend",
          "value": {
            "from_address": "cosmos1x7f0aqgucrwkefkdz9de2ddm2lq59vydh2w6vc",
            "to_address": "cosmos19azqtluqt9ap2elfkv3eewe8nmmfuqpfeepw5n",
            "amount": [
              {
                "denom": "stake",
                "amount": "10000"
              }
            ]
          }
        }
      ],
      "fee": {
        "amount": [],
        "gas": "200000"
      },
      "signatures": [
        {
          "public_key": "8WWOMkEEvB/01DN7NjTU2SU2h4OSqghy4rllLXd0woeb8CAT0+VlPryUdbiasLcKKDt7w8AzIHLw27q2GYnYlVx4rMnZbg==",
          "signature": "WdQDY4aodLg2TnF6T65N+/my1sKI1dyO/e3Dk3cChupnGPvidybkv3s6mTfCjK1LHSZWONf1qQw3f/82YlwbmAE="
        }
      ],
      "memo": ""
    }
  },
  "timestamp": "2020-05-09T08:14:41Z"
}

**Comment by fedekunze** [comment]
Hi @landoyjx, did you define the fees using the `--fees` flag during `emintcli tx send mykey mykey2 1000stake`?

**Comment by landoyjx** [comment]
> Hi @landoyjx, did you define the fees using the `--fees` flag during `emintcli tx send mykey mykey2 1000stake`?

No. Yes, it should define fees in cli. if not it will be no fee, should the tx have a default fee?

Find another bug. --gas-prices only support decimal price not support integer price, as not support "10 stake", but support "10.0 stake". It should fix the regex in gasprice checking.

**Comment by fedekunze** [comment]
>  if not it will be no fee, should the tx have a default fee?

That's up to the sender, you can send 0 fee transaction if the block proposer accepts 0 as minimum fee.

> Find another bug. --gas-prices only support decimal price not support integer price, as not support "10 stake", but support "10.0 stake". It should fix the regex in gasprice checking.

👍 Mind creating an issue on the [cosmos SDK](https://github.com/cosmos/cosmos-sdk/issues/new)?

**Comment by fedekunze** [comment]
closing this issue as the underlying problem was resolved
