### ISSUE TITLE
unrecognized public key type: <nil>: invalid pubkey

### ISSUE THREAD

**Issue by Lunagram** [cosmos/ethermint#291]
__System info:__

commit c7d89e3d561e594fc4a2efab8130f10cc8d67d08

__Steps to reproduce:__

1. Send to a signed tx to LCD (@POST /txs)

{
	"tx": {
		"msg": [{...}],
		"fee": {...},
		"signatures": [{
			"pub_key": {
				"type": "tendermint/PubKeySecp256k1",
				"value": "A7DSqy3UCEp6RR3ssW4JnsmOruqeSROnQMJ0a4OHMK8+"
			},
			"signature": "jNC9h1u2oWM9nx62uyxqFQvLjgtKC/l5KGh0N6ZpMep8WPg/JFBQ5ztA8V+2925wo9z1nQNE294er3JZNpWjnQ=="
		}],
		"memo": ""
	},
	"mode": "sync"
}

__Actual behavior:__ 
tx send failed.

{
  "code": 8,
  "height": "0",
  "raw_log": "unrecognized public key type: <nil>: invalid pubkey",
  "txhash": "E4AE84EBF018A69DB8C405B4D6DBB4B7D48EF06B80E81C92D3DC0681460B35DE"
}

__Expected behavior:__
This request should be processed normally.

I have to follow the 'public key' field type used on cosmos-hub for multi chain support. (pub_key.type and pub_key.value)

but currently ethermint does not support 
	"pub_key": {
		"type": "tendermint/PubKeySecp256k1",
		"value": "A7DSqy3UCEp6RR3ssW4JnsmOruqeSROnQMJ0a4OHMK8+"
	}

**Comment by fedekunze** [comment]
Correct, Etheremint currently doesn't support tendermint's `PubKeySecp256k1`. It instead uses ethereum's  `secp256k1` curve. You can generate a valid key with the `emintcli keys add` command

**Comment by Lunagram** [comment]
Omg, My problem is big... I use one goleng binary (similar gaiacli) for my android app to manage the account and sign the transaction. Since the default file size is too large, emintcli cannot be added to the app.

Is there any idea? I want to cry...

**Comment by fedekunze** [comment]
No worries, we're here to help 🙂 Can you explain to me a bit more about your use case and its current architecture? You can find me on the [Cosmos Discord](https://discord.com/invite/cr7N47p) too if you want to chat there.
