### ISSUE TITLE
panic: emintcli tx distribution fund-community-pool 1000stake --from mykey

### ISSUE THREAD

**Issue by landoyjx** [cosmos/ethermint#294]
$ emintcli tx distribution fund-community-pool 1000stake --from mykey
panic: Cannot encode unregistered concrete type types.MsgFundCommunityPool.

goroutine 1 [running]:
github.com/cosmos/cosmos-sdk/x/auth/client.CompleteAndBroadcastTxCLI(0xc000d96c60, 0x52e18c0, 0xc0006b65a0, 0x0, 0xb, 0x30d40, 0x3ff0000000000000, 0x0, 0x5bc9ed8, 0x1, ...)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/auth/client/tx.go:91 +0xbb9
github.com/cosmos/cosmos-sdk/x/auth/client.GenerateOrBroadcastMsgs(0xc000eae5a0, 0x14, 0x14, 0x52e8d20, 0xc000eb09c0, 0x5bc9ed8, 0x1, 0x0, 0x0, 0x0, ...)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/auth/client/tx.go:51 +0x15c
github.com/cosmos/cosmos-sdk/x/distribution/client/cli.GetCmdFundCommunityPool.func1(0xc00074bb80, 0xc00070d890, 0x1, 0x3, 0x0, 0x0)
	/Users/lando/go/pkg/mod/github.com/cosmos/cosmos-sdk@v0.34.4-0.20200403200637-7f78e61b93a5/x/distribution/client/cli/tx.go:296 +0x403
github.com/spf13/cobra.(*Command).execute(0xc00074bb80, 0xc00070d800, 0x3, 0x3, 0xc00074bb80, 0xc00070d800)
	/Users/lando/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:838 +0x453
github.com/spf13/cobra.(*Command).ExecuteC(0xc0001d22c0, 0x44ae5b0, 0xc0001d22c0, 0x4ef3a16)
	/Users/lando/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:943 +0x317
github.com/spf13/cobra.(*Command).Execute(...)
	/Users/lando/go/pkg/mod/github.com/spf13/cobra@v0.0.7/command.go:883
github.com/tendermint/tendermint/libs/cli.Executor.Execute(0xc0001d22c0, 0x50ffdb0, 0x2, 0xc00068d6e0)
	/Users/lando/go/pkg/mod/github.com/tendermint/tendermint@v0.33.3/libs/cli/setup.go:89 +0x3c
main.main()
	/Users/lando/test/ethermint/cmd/emintcli/main.go:82 +0x620

**Comment by fedekunze** [comment]
ohhh nice catch! The MsgFundCommunityPool is not registered on the SDK amino codec. I'll transfer the issue

**Comment by fedekunze** [comment]
closed via https://github.com/cosmos/cosmos-sdk/pull/6211
