### ISSUE TITLE
cannot run truffle tests for aragon-court

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#297]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
truffle version 5.1.24

__Steps to reproduce:__

1. I was trying to test aragon-court, but I imagine this is similar for any truffle tests using truffle v5

```
git clone https://github.com/aragon/aragon-court 
cd aragon-court
```
2. start ethermint node + rpc client
3. add this line to `truffle-config.js`:
```
TruffleConfig.networks.rpc.network_id = 8
```

4. `truffle test --network rpc`

5. seems like `.New()` doesn't work with truffle, or perhaps not with certain contracts

__Expected behavior:__ [What you expected to happen]
truffle tests run

__Actual behavior:__ [What actually happened]
failures

```

  Contract: Arbitrable
    1) "before each" hook: create arbitrable instance for "supports ERC165"
```
__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
can we try to reproduce this again?
