### ISSUE TITLE
hey,i have a problem with deploy contract about ethermint.

### ISSUE THREAD

**Issue by stonehost** [cosmos/ethermint#300]
deployment contract failed

![image](https://user-images.githubusercontent.com/64956887/82000840-21825980-968c-11ea-892f-ebe2218b3dc4.png)

![image](https://user-images.githubusercontent.com/64956887/82000819-13ccd400-968c-11ea-8150-0550e6028594.png)

**Comment by stonehost** [comment]
user metamask deploy
![image](https://user-images.githubusercontent.com/64956887/82000868-35c65680-968c-11ea-824d-0df5dab01511.png)

**Comment by noot** [comment]
@stonehost the receipt status is 0, so it looks like deployment failed. could you try increasing the gas limit?

**Comment by stonehost** [comment]
![image](https://user-images.githubusercontent.com/64956887/82277104-a685af80-99b9-11ea-990a-b7b12702a8f5.png)

**Comment by stonehost** [comment]
![image](https://user-images.githubusercontent.com/64956887/82277140-bac9ac80-99b9-11ea-9fdf-b3e8e9a70f41.png)
![image](https://user-images.githubusercontent.com/64956887/82277167-cae18c00-99b9-11ea-8b03-6102e439d01b.png)

**Comment by stonehost** [comment]
already setting

**Comment by noot** [comment]
@stonehost please pull from development and `make install` again, I believe the issue has been fixed. let me know if you are still seeing it!

**Comment by stonehost** [comment]
ok,thanks
