### ISSUE TITLE
test eth_getBlockByHash

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#301]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. test TestBlockBloom_Hash
```
 ETHERMINT_NODE_HOST=http://localhost:8545 ETHERMINT_INTEGRATION_TEST_MODE=stable go test ./tests/... -test.v -test.run ^TestBlockBloom_Hash
```

2. the test fails because the call to `eth_getBlockByHash` fails to find a block number with that hash

__Expected behavior:__ [What you expected to happen]

block is found

__Actual behavior:__ [What actually happened]

block hash to height mapping cannot be found

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by ayeteng** [comment]
eth_getBlockByNumber should return the block hash but not working either.
