### ISSUE TITLE
truffle migrate not working

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#305]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. following steps here to get pet-shop tutorial:
https://www.trufflesuite.com/tutorials/pet-shop

```
mkdir pet-shop && cd pet-shop
truffle unbox pet-shop
```
update truffle-config.js to point to localhost:8545

2. `truffle migrate`

__Expected behavior:__ [What you expected to happen]
contracts get deployed

__Actual behavior:__ [What actually happened]
```
$ truffle migrate

Compiling your contracts...
===========================
> Everything is up to date, there is nothing to compile.



Migrations dry-run (simulation)
===============================
> Network name:    'development-fork'
> Network id:      8
> Block gas limit: 4294967295 (0xffffffff)


1_initial_migration.js
======================

   Deploying 'Migrations'
   ----------------------

Error:  *** Deployment Failed ***

"Migrations" -- Returned error: account cosmos1ckta7fd00vsm9gectglcd034em3zyek34lkf4l does not exist: unknown address.

    at /home/elizabeth/.nvm/versions/node/v10.12.0/lib/node_modules/truffle/build/webpack:/packages/deployer/src/deployment.js:364:1
    at process._tickCallback (internal/process/next_tick.js:68:7)
Truffle v5.1.24 (core: 5.1.24)
Node v10.12.0
```

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
> `"Migrations" -- Returned error: account cosmos1ckta7fd00vsm9gectglcd034em3zyek34lkf4l does not exist: unknown address.`

Uhh why does it return a cosmos address? Shouldn't it return it in hex format `0x...`?

**Comment by noot** [comment]
> > `"Migrations" -- Returned error: account cosmos1ckta7fd00vsm9gectglcd034em3zyek34lkf4l does not exist: unknown address.`
> 
> Uhh why does it return a cosmos address? Shouldn't it return it in hex format `0x...`?

yeah it should, I'm not sure why it's returning a cosmos one...

also, it could be that it's looking for the wrong account for some reason, that's just the error message that gets printed out. that's what I saw before with the Aragon deployer

**Comment by ChainCoderX** [comment]
I have the problem too.
@fedekunze 

Could you share us an example ?

**Comment by noot** [comment]
looks like `truffle migrate --reset` works to an extent, but then runs out of gas:
```
I[2020-06-16|18:55:10.996] Added good transaction                       module=mempool tx=844C049EB8D28A71D12721917AAF5C057FA6B59105DDD3C21B8CCCB172CF0B39 res="&{CheckTx:log:\"[]\" gas_wanted:6721975 gas_used:85688 }" height=3 total=1
I[2020-06-16|18:55:13.607] Executed block                               module=state height=4 validTxs=1 invalidTxs=0
I[2020-06-16|18:55:13.611] Committed state                              module=state height=4 txs=1 appHash=D519C6280A648D12FBB99413685FE32762359E5FCCEB7C4DE370ED027DF408CC
I[2020-06-16|18:55:14.025] Rejected bad transaction                     module=mempool tx=3CF03AC66683E59F63097908AB61449DF9D25A97DBD256672D1FAC912F9E7D64 peerID= res="&{CheckTx:code:5 log:\"sender balance < tx gas cost (327802500000000000photon < 672197500000000000photon): insufficient funds\" gas_used:2489 codespace:\"sdk\" }" err=null
```

```
$ truffle migrate --reset
Using network 'development'.

Running migration: 1_initial_migration.js
  Deploying Migrations...
  ... 0x844c049eb8d28a71d12721917aaf5c057fa6b59105ddd3c21b8cccb172cf0b39
  Migrations: 0x5cb5fda95642fb63e0303ca2ac7690a590882954
Saving successful migration to network...
  ... 0x3cf03ac66683e59f63097908ab61449df9d25a97dbd256672d1fac912f9e7d64
```

a simple contract deploy shouldn't cost >1 eth
