### ISSUE TITLE
load aragon contracts at genesis

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#313]
__Proposal:__ [Description of the feature]

- add aragonOS contracts (and app contracts) to the genesis state

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by fedekunze** [comment]
I think this issue is resolved?
