### ISSUE TITLE
use metamask,tip invalid nonce

### ISSUE THREAD

**Issue by stonehost** [cosmos/ethermint#316]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. [First Step]
use metamask transfer or deploy contact
2. [Second Step]
tip invalid nonce
3. [and so on...]

![image](https://user-images.githubusercontent.com/64956887/82882648-f218fa00-9f73-11ea-9ad3-93a63550e87b.png)

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by stonehost** [comment]
tip invalid nonce
![image](https://user-images.githubusercontent.com/64956887/82882791-22f92f00-9f74-11ea-98d3-a3736964d9df.png)

**Comment by noot** [comment]
hey, are you using the latest development branch?

**Comment by noot** [comment]
closing for now, please re-open if you are still having issues
