### ISSUE TITLE
contract call that should emit event and return data doesn't, but doesn't revert

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#323]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. `git fetch && git checkout noot/genesis-contracts`
2. `go test ./x/evm/ -testify.m TestNewENS -v`
3. this test deploys `ENSFactory` and calls `newENS` on it, which should return an `ENS` address as well as create some logs. however neither of these things happen, but the call doesn't revert either
https://github.com/aragon/aragonOS/blob/next/contracts/factory/ENSFactory.sol#L19

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]
note that calling `newENS` works with truffle/web3, so not sure why this is a different case

**Comment by maektwain** [comment]
Trying to dial this using the command line: 

`npx truffle exec  --network avash scripts/deploy/test-ens.js`

`Deploying ENSFactory...`

It is just stuck at the above console
