### ISSUE TITLE
Event filter of transactions

### ISSUE THREAD

**Issue by ayeteng** [cosmos/ethermint#330]
__Proposal:__ [Description of the feature]
Implement the event filter to get the relevant block by filtering the required condition

__Current behavior:__ [What currently happens]
```
event_filter = getattr(store_var_contract.events, 'MyEvent').createFilter(fromBlock=0, toBlock='latest')
all_entries = event_filter.get_all_entries()
print(all_entries)
>[]

```
__Desired behavior:__ [What you would like to happen]
Filters provide notifications of certain events taking place in the Ethereum network.
Look forward to find event filter function enabled.
https://web3py.readthedocs.io/en/stable/filters.html

__Use case:__ [Why is this important (helps with prioritizing requests)]
If you want to find the transaction on the chain, you need to use filter function.
Requests may be closed if we're not actively planning to work on them.

**Comment by fedekunze** [comment]
hi @ayeteng, this is currently being worked on #308

**Comment by noot** [comment]
@fedekunze I think this is more related to the `eth_newFilter` function, which is implemented. 

@ayeteng  could you confirm that there are in fact logs being created by using `eth_getTransactionLogs` or `eth_getTransactionReceipt`? if there are logs and the filter isn't picking them up could you please post your contract?

**Comment by ayeteng** [comment]
This is my test contract and test code.
The smart contract setVar function will emit the event when setVar.
https://gist.github.com/ayeteng/48bc63d5b7500f94901389b888912a7b
The function can get the event log by receipt. But it cannot get the event log by event filter
https://gist.github.com/ayeteng/ca3df35d550c2a054ebc95f2ff013df0

**Comment by noot** [comment]
thanks! I'll take a look soon
