### ISSUE TITLE
gas estimation fails with remix

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#339]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. start ethermint node and RPC server
2. open remix and compile a default contract
3.`emintcli keys unsafe-export-eth-key mykey` and import private key into metamask
4. switch metamask to localhost:8545
5. in remix change environment to injected web3 and hit deploy
6. see error:
```
Gas estimation errored with the following message (see below). The transaction execution will likely fail. Do you want to force sending?
[object Object] { "code": -32000, "message": "internal error" }
```
if you hit `submit transaction` the contract deployment does work.

__Expected behavior:__ [What you expected to happen]
gas estimation works 

__Actual behavior:__ [What actually happened]
gas estimation fails

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
It'd be nice to see as well what's the estimation from Remix vs the actual gas consumption from Ethermint
