### ISSUE TITLE
How to build Multi-node about ethermint？

### ISSUE THREAD

**Issue by stonehost** [cosmos/ethermint#347]
__Proposal:__ [Description of the feature]

How to build Multi-node about ethermint？

__Current behavior:__ [What currently happens]

__Desired behavior:__ [What you would like to happen]

__Use case:__ [Why is this important (helps with prioritizing requests)]

Requests may be closed if we're not actively planning to work on them.

**Comment by fedekunze** [comment]
Hi @stonehost, we created a `testnet` command to start the setup for an `n` validator node local-testnet. Instructions are on #378

**Comment by stonehost** [comment]
@fedekunze thanks, very good
