### ISSUE TITLE
consensus error

### ISSUE THREAD

**Issue by ChainCoderX** [cosmos/ethermint#348]
env:  MachineA , MachineB

1. comment the cmd (emintd start)  in  script (init.sh) on two machines.
2. run script( init.sh) on two machines.
3. copy MachineA/.emintd/config/gentx/xxxxxxx.json to MachineB/.emintd/config/gentx/xxxxxxx.json
4. get the address  by the cmd (emintcli keys list) on  MachineA. 
5. run cmd(emintd add-genesis-account  (step4 addr) 1000000000000000000photon,1000000000000000000stake) on MachineB
6. run cmds(emintd collect-gentxs and mintd emintd validate-genesis ) on MachineB
7. copy  MachineB/.emintd/config/genesis.json to MachineA/.emintd/config/genesis.json.
8. get the nodeId of MachineB by the cmd(emintd   tendermint  show-node-id) and IP address.
9. edit file(MachineA/.emintd/config/config.toml) replace persistent_peers value .
10. run cmd(emintd start --pruning=nothing --rpc.unsafe --log_level "main:info,state:info,mempool:info" --trace) on two machines.
11. run rest-server(emintcli rest-server --laddr "tcp://0.0.0.0:8545" --unlock-key mykey)

12. deploy smart contract(erc20) and  call the balanceOf of contract.

validator errors:
ECDF79B6EC5D81C1D94570EDE5A5F6256C69899A5DC5085EEEC0B1FF5"
E[2020-06-30|06:27:55.362] enterPrevote: ProposalBlock is invalid       module=consensus height=45 round=58 err="wrong Block.Header.AppHash.  Expected 1B1DD507FFAE464F4FBD32BB60D2E9EB6DAD727A06E7C930C5D9B7C8C640EA30, got 9231237ECDF79B6EC5D81C1D94570EDE5A5F6256C69899A5DC5085EEEC0B1FF5"
E[2020-06-30|06:29:56.987] enterPrevote: ProposalBlock is invalid       module=consensus height=45 round=60 err="wrong Block.Header.AppHash.  Expected 1B1DD507FFAE464F4FBD32BB60D2E9EB6DAD727A06E7C930C5D9B7C8C640EA30, got 9231237ECDF79B6EC5D81C1D94570EDE5A5F6256C69899A5DC5085EEEC0B1FF5"
E[2020-06-30|06:32:02.609] enterPrevote: ProposalBlock is invalid       module=consensus height=45 round=62 err="wrong Block.Header.AppHash.  Expected 1B1DD507FFAE464F4FBD32BB60D2E9EB6DAD727A06E7C930C5D9B7C8C640EA30, got 9231237ECDF79B6EC5D81C1D94570EDE5A5F6256C69899A5DC5085EEEC0B1FF5"
E[2020-06-30|06:34:12.333] enterPrevote: ProposalBlock is invalid       module=consensus height=45 round=64 err="wrong Block.Header.AppHash.  Expected 1B1DD507FFAE464F4FBD32BB60D2E9EB6DAD727A06E7C930C5D9B7C8C640EA30, got 9231237ECDF79B6EC5D81C1D94570EDE5A5F6256C69899A5DC5085EEEC0B1FF5"
E[2020-06-30|06:36:25.952] enterPrevote: ProposalBlock is invalid       module=consensus height=45 round=66 err="wrong Block.Header.AppHash.  Expected 1B1DD507FFAE464F4FBD32BB60D2E9EB6DAD727A06E7C930C5D9B7C8C640EA30, got 9231237ECDF79B6EC5D81C1D94570EDE5A5F6256C69899A5DC5085EEEC0B1FF5"
E[2020-06-30|06:38:43.570] enterPrevote: ProposalBlock is invalid       module=consensus height=45 round=68 err="wrong Block.Header.AppHash.  Expected 1B1DD507FFAE464F4FBD32BB60D2E9EB6DAD727A06E7C930C5D9B7C8C640EA30, got 9231237ECDF79B6EC5D81C1D94570EDE5A5F6256C69899A5DC5085EEEC0B1FF5"
E[2020-06-30|06:41:05.188] enterPrevote: ProposalBlock is invalid       module=consensus height=45 round=70 err="wrong Block.Header.AppHash.  Expected 1B1DD507FFAE464F4FBD32BB60D2E9EB6DAD727A06E7C930C5D9B7C8C640EA30, got 9231237ECDF79B6EC5D81C1D94570EDE5A5F6256C69899A5DC5085EEEC0B1FF5"

**Comment by edgelang** [comment]
Hi, I also have this problem. Have you solved it?

**Comment by ChainCoderX** [comment]
No,
we try the below codes to fix the problem in the func(handleMsgEthermint) 

    if st.Simulate {
        st.Csdb = st.Csdb.Copy()
    }

but that does not work good,
if you transfer  contract coin then  immediate call the balanceOf of contract by receiver address,  the problem happen again.

**Comment by edgelang** [comment]
This problem does not occur in the single-node test network call contract. This problem appears in the test network of multiple consensus nodes. Is there something wrong with our configuration?

**Comment by ChainCoderX** [comment]
@edgelang 
yea, If you just run single-node, there is no different app hash,（only one app hash） 

no, there is nothing wrong with your configuration.

**Comment by edgelang** [comment]
Ok thanks, can i take a look at your gemness.json file, I want to see the difference

**Comment by ChainCoderX** [comment]
[genesis.json.zip](https://github.com/ChainSafe/ethermint/files/4862164/genesis.json.zip)

this is my genesis.json file.

**Comment by ChainCoderX** [comment]
@noot 

can you help me with docs on how to fix this?

**Comment by edgelang** [comment]
thank you,
This is my genesis.json file, which is roughly the same as yours
[genesis.zip](https://github.com/ChainSafe/ethermint/files/4862190/genesis.zip)

**Comment by noot** [comment]
@wade-liwei hey, @fedekunze is working on this is now
