### ISSUE TITLE
Consensus failure

### ISSUE THREAD

**Issue by mhxw** [cosmos/ethermint#359]
env: MachineA , MachineB,MachineC,MachineD

1. comment the cmd (emintd start) in script (init.sh) on four machines.

2. run script( init.sh) on four machines.

3. copy MachineA/.emintd/config/gentx/xxxxxxx.json to MachineD/.emintd/config/gentx/xxxxxxx.json
copy MachineB/.emintd/config/gentx/xxxxxxx.json to MachineD/.emintd/config/gentx/xxxxxxx.json
copy MachineC/.emintd/config/gentx/xxxxxxx.json to MachineD/.emintd/config/gentx/xxxxxxx.json

4. get the address by the cmd (emintcli keys list) on MachineA.(MachineB MachineC same step)

5. run cmd(emintd add-genesis-account (step4 addr) 1000000000000000000photon,1000000000000000000stake) on MachineD

6. run cmds(emintd collect-gentxs and mintd emintd validate-genesis ) on MachineD

7. copy MachineD/.emintd/config/genesis.json to MachineA/.emintd/config/genesis.json(MachineB MachineC same step).

8. get the nodeId of MachineD by the cmd(emintd tendermint show-node-id) and IP address(MachineA MachineB MachineC same step).

9. edit file(MachineA/.emintd/config/config.toml) replace persistent_peers value(MachineB MachineC same step). .

10. run cmd(emintd start --pruning=nothing --rpc.unsafe --log_level "main:info,state:info,mempool:info" --trace) on two machines.

11. run rest-server(emintcli rest-server --laddr "tcp://0.0.0.0:8545" --unlock-key mykey)

12. deploy smart contract(erc20) and call the balanceOf of contract.

![image](https://user-images.githubusercontent.com/32643286/86572321-5b455180-bfa5-11ea-928e-5d5e144bfe61.png)

E[2020-07-06|16:15:39.118] enterPrevote: ProposalBlock is invalid       module=consensus height=75 round=1 err="wrong Block.Header.AppHash.  Expected 6561998D069E80E80B7E1AD6200C17BD91B566D6E6059EC935E8081884562E93, got FCD64FEA9B3D4CD94965512EF80E7F892EAA68FA3EFA8148925F8CBD440C689D"
E[2020-07-06|16:15:39.319] CONSENSUS FAILURE!!!                         module=consensus err="enterPrecommit: +2/3 prevoted for an invalid block: wrong Block.Header.AppHash.  Expected 6561998D069E80E80B7E1AD6200C17BD91B566D6E6059EC935E8081884562E93, got FCD64FEA9B3D4CD94965512EF80E7F892EAA68FA3EFA8148925F8CBD440C689D" stack="goroutine 803 [running]:\nruntime/debug.Stack(0xc004521418, 0x13b8680, 0xc003488d70)\n\t/usr/local/go/src/runtime/debug/stack.go:24 +0x9d\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine.func2(0xc0010c1180, 0x17af650)\n\t/root/goApps/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:617 +0x57\npanic(0x13b8680, 0xc003488d70)\n\t/usr/local/go/src/runtime/panic.go:679 +0x1b2\ngithub.com/tendermint/tendermint/consensus.(*State).enterPrecommit(0xc0010c1180, 0x4b, 0x1)\n\t/root/goApps/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1234 +0x1570\ngithub.com/tendermint/tendermint/consensus.(*State).addVote(0xc0010c1180, 0xc003491680, 0xc001165a40, 0x28, 0x0, 0x8, 0xc004521a38)\n\t/root/goApps/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1870 +0xdfa\ngithub.com/tendermint/tendermint/consensus.(*State).tryAddVote(0xc0010c1180, 0xc003491680, 0xc001165a40, 0x28, 0x2f8318e5d694d4ab, 0x106, 0xfe)\n\t/root/goApps/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:1707 +0x67\ngithub.com/tendermint/tendermint/consensus.(*State).handleMsg(0xc0010c1180, 0x1a11020, 0xc000c87c20, 0xc001165a40, 0x28)\n\t/root/goApps/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:713 +0x252\ngithub.com/tendermint/tendermint/consensus.(*State).receiveRoutine(0xc0010c1180, 0x0)\n\t/root/goApps/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:648 +0x6eb\ncreated by github.com/tendermint/tendermint/consensus.(*State).OnStart\n\t/root/goApps/pkg/mod/github.com/tendermint/tendermint@v0.33.4/consensus/state.go:335 +0x13a\n"
E[2020-07-06|16:17:46.727] dialing failed (attempts: 8): auth failure: secret conn failed: EOF module=pex addr=015128f1b7a6a1472df3df26f9a6f57d0469d673@47.103.38.41:26656
E[2020-07-06|16:22:16.729] dialing failed (attempts: 9): auth failure: secret conn failed: EOF module=pex addr=015128f1b7a6a1472df3df26f9a6f57d0469d673@47.103.38.41:26656

**Comment by mhxw** [comment]
open

**Comment by fedekunze** [comment]
this is actually now resolved on development 👍

**Comment by mhxw** [comment]
I use the latest development, Still report this error。
![image](https://user-images.githubusercontent.com/32643286/88920862-2379b300-d2a0-11ea-8ff7-eb710fa1f3b5.png)

**Comment by noot** [comment]
@holechain how many nodes are you running and how are you starting them? are you sending some transactions as well, if so what kind?

**Comment by mhxw** [comment]
I am running 4 nodes.  Run the program in the way mentioned in the issues above.  Sending the transfer shows success, but the deployment of the erc20 contract prompts this error.

**Comment by noot** [comment]
@holechain thanks for the info! will take a look soon.

**Comment by fedekunze** [comment]
also ref #179, #348

**Comment by fedekunze** [comment]
fixed on v0.1.0

**Comment by mhxw** [comment]
I use the latest v0.1.0, Still report this error。
![image](https://user-images.githubusercontent.com/32643286/91810637-d141fe00-ec60-11ea-85d8-2b31ae985a3f.png)
