### ISSUE TITLE
Pending State Query

### ISSUE THREAD

**Issue by ColinSchwarz** [cosmos/ethermint#369]
Implement a way to handle pending state queries through the Web3 API (Transactions in Cosmos are processed at end of block, in some niche cases people use that pending state). The first task would be to track pending transactions to be able to issue correct pending nonce when letting RPC API/ CLI default it for the transaction builder (Cosmos queries current state for defaulting nonce in their CLI so this would be a feature to match Geth because they default nonce based on the pending state). 

The final step of this deliverable would be to improve the testing/compatibility of Web3 API through existing tooling or scripts to compare output against Geth.

**Comment by fedekunze** [comment]
closed via #571
