### ISSUE TITLE
document how to present two kinds of address (cosmos and eth)

### ISSUE THREAD

**Issue by ChainCoderX** [cosmos/ethermint#406]
how to present two kinds of address(cosmos and eth) for user ?

**Comment by fedekunze** [comment]
For ethereum address you can use the `eth_accounts` JSON-RPC method. For the cosmos ones you can either use `emintcli keys show <key> -a` or `emintcli query account <address>`

**Comment by fedekunze** [comment]
how are you querying the addresses and displaying it to the user? Do you want us to include the Ethereum address on the cosmos `EthAccount` type too?

**Comment by fedekunze** [comment]
I think we can update the documentation to explain this in more detail. I'll update the title 👍
