### ISSUE TITLE
eth_getBlockByNumber returns error

### ISSUE THREAD

**Issue by araskachoi** [cosmos/ethermint#418]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. start the network (run emintd & emintcli rest-server)
2. wait about 30 seconds to let blocks produce (~20 blocks)
3. run command `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0x1", true],"id":1}' -H "Content-Type: application/json" http://localhost:8545` (should work)
3. run command `curl -X POST --data '{"jsonrpc":"2.0","method":"eth_getBlockByNumber","params":["0xB", true],"id":1}' -H "Content-Type: application/json" http://localhost:8545` (doesn't work)
__Expected behavior:__ [What you expected to happen]
should give you a non-error return with block information
example:
```
{"jsonrpc":"2.0","id":1,"result":{"difficulty":null,"extraData":"0x0","gasLimit":"0xffffffff","gasUsed":"0x0","hash":"0x89fc197ef6963da6393fca4ceee92be27a6a01963ce9c648388882c7d15f9183","logsBloom":"0x00000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000000","miner":"0x0000000000000000000000000000000000000000","nonce":null,"number":"0x1","parentHash":"0x","sha3Uncles":null,"size":"0x98","stateRoot":"0x","timestamp":"0x5f244bfb","totalDifficulty":null,"transactions":[],"transactionsRoot":"0x","uncles":[]}}
```
__Actual behavior:__ [What actually happened]
```
{"jsonrpc":"2.0","id":1,"error":{"code":-32000,"message":"internal error"}}
```
__Additional info:__ [Include gist of relevant config, logs, etc.]
@noot suggests that this could be a parsing issue
@fedekunze has this issue come up before? has there been any changes to ethermint to cause this?

**Comment by noot** [comment]
can't seem to recreate this, could you confirm if this is still an issue?
