### ISSUE TITLE
Self node in addrbook.json and node tries to dial itself

### ISSUE THREAD

**Issue by ColinSchwarz** [cosmos/ethermint#424]
Ref: https://github.com/tendermint/tendermint/issues/3716#issuecomment-668768730

The errors occurs when running the [multi-node local,l automated testnet](https://docs.ethermint.zone/quickstart/testnet.html) setup though `make locanet-start` and Docker.

**Comment by tac0turtle** [comment]
Hey tried running the `make localnet-start` but ran into this error: 
```
if ! [ -f build/node0/ethermintd/config/genesis.json ]; then docker run --rm -v /Users/markobaricevic/code/CoTend/ethermint/build:/ethermint:Z ethermintd/node "ethermintd testnet --v 4 -o /ethermint --starting-ip-address 192.168.10.2 --keyring-backend=test"; fi
Password for account 'node0' :
ERROR: signing algorithm must be eth_secp256k1, got secp256k1
make: *** [localnet-start] Error 1
```

is this expected?

**Comment by araskachoi** [comment]
fix has been made and merged to development branch. Reopen if issue is still occuring
