### ISSUE TITLE
Single Ethermint binary

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ethermint#433]
Create a single binary for ethermin instead of the 2 existing ones. `ethermintcli` should be merged into `ethermintd0`

Ref issue: https://github.com/cosmos/cosmos-sdk/issues/6419
Ref implementation: https://github.com/cosmos/cosmos-sdk/pull/6595

**Comment by J-Thompson12** [comment]
Unable to continue on this until we ipdate to a newer version of cosmos
