### ISSUE TITLE
Photon base denom unit precision

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ethermint#434]
Discuss Photon base denomination precision options:

- `0` (current implementation)
- `6`:  `1 photon = 1x10⁶ μphoton`. Eg: `1 atom -> 1x10⁶ μatom`
- `18`:  `1 photon = 1x10¹⁸ aphoton` (i.e [atto](https://en.wikipedia.org/wiki/Atto-)). Eg: `1 ETH -> 1x10¹⁸  wei`

Ref: [SI](https://en.wikipedia.org/wiki/International_System_of_Units) prefixes for precision units

**Comment by fedekunze** [comment]
@okwme thoughts?

**Comment by okwme** [comment]
sounds great!
this distinction would eventually make its way into the coin metadata work that bez implemented right?

**Comment by fedekunze** [comment]
I think keeping the same base denomination with Ethereum makes sense so I'd personally go for option 3)
