### ISSUE TITLE
ProposalBlock is invalid

### ISSUE THREAD

**Issue by araskachoi** [cosmos/ethermint#450]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

$ ethermintd version
0.0.0-11-gca0a79f

ID=Ubuntu
RELEASE=18.04
CODENAME=bionic
DESCRIPTION="Ubuntu 18.04.5 LTS"

__Error:__

Sending a transaction to a node in the testnet caused an error that halted the chain. The error message is: `enterPrevote: ProposalBlock is invalid `. This seems to 

Node0 Log: 
<img width="1440" alt="testnode0" src="https://user-images.githubusercontent.com/13338103/90449077-87231f00-e09b-11ea-9439-ec87ebf07123.png">

Node1 Log:
<img width="1440" alt="testnode1" src="https://user-images.githubusercontent.com/13338103/90449087-8ab6a600-e09b-11ea-810e-e5e73a4510a5.png">

Tx sent:
<img width="1440" alt="tx" src="https://user-images.githubusercontent.com/13338103/90449094-8f7b5a00-e09b-11ea-927b-2bf3e08628fc.png">

__Steps to reproduce:__

1. Copy the proper files to correct directories
```
scp -r emint_2nodes/node0/ethermintd/ root@<node0_IP>:~/.ethermintd
scp -r emint_2nodes/node0/ethermintcli root@<node0_IP>:~/.ethermintcli

scp -r emint_2nodes/node1/ethermintd/ root@<node1_IP>:~/.ethermintd
scp -r emint_2nodes/node1/ethermintcli root@<node1_IP>:~/.ethermintcli
```

[emint_2nodes.zip](https://github.com/ChainSafe/ethermint/files/5086994/emint_2nodes.zip)

2. Start the nodes:
```
# node 0
ethermintcli config keyring-backend test
ethermintd start > emintd.log &
emintcli rest-server --laddr "tcp://<node0_IP>:8545" --unlock-key node0 --chain-id 1470189191838651654 --trace > emintcli.log &

# node 1
ethermintcli config keyring-backend test
ethermintd start > emintd.log &
emintcli rest-server --laddr "tcp://<node1_IP>:8545" --unlock-key node0 --chain-id 1470189191838651654 --trace > emintcli.log &
```

3. Send a transaction to the network:
```
curl -X POST --data '{"jsonrpc":"2.0","method":"eth_sendTransaction","params": [{"from": "<node0_accountHexAddress>", "to": "0x7f9f463c4d57b1bd3e3b79051e6c5ab703e803d9", "value": "0xA", "gasLimit": "0x5208", "gasPrice": "0xA"}],"id":1}' -H "Content-Type: application/json" <node0_IP>:8545
```

4. View the output of the network:
```
tail -f emintd.log
```

__Expected behavior:__ Should generate blocks without failure to consensus
```
I[2020-08-17|19:42:34.230] Executed block                               module=state height=2 validTxs=0 invalidTxs=0
I[2020-08-17|19:42:34.232] Committed state                              module=state height=2 txs=0 appHash=D081986AE0FCFC33BA6F65E16124AA81695B36030779827B4F9BA9FEDFB0E793
I[2020-08-17|19:42:39.550] Executed block                               module=state height=3 validTxs=0 invalidTxs=0
I[2020-08-17|19:42:39.552] Committed state                              module=state height=3 txs=0 appHash=C5F286C83AF8112E0333E9F5B397C95F491F11ED041D708199DFF3DFE5E4A53F
I[2020-08-17|19:42:44.963] Executed block                               module=state height=4 validTxs=0 invalidTxs=0
```

__Actual behavior:__ Blocks remain stuck with error message
```
E[2020-08-17|19:47:56.264] enterPrevote: ProposalBlock is invalid       module=consensus height=62 round=0 err="wrong Block.Header.AppHash.  Expected 1EAB96473578BEBA876CA9D204E64348C2DB2F3090753B53E7C8F880872C0A2A, got E5401BB87BF21409E6BE6BC740AE6E7318F0587CF9A2E0AFF74A6570E5753A3D"
E[2020-08-17|19:48:01.997] enterPrevote: ProposalBlock is invalid       module=consensus height=62 round=2 err="wrong Block.Header.AppHash.  Expected 1EAB96473578BEBA876CA9D204E64348C2DB2F3090753B53E7C8F880872C0A2A, got E5401BB87BF21409E6BE6BC740AE6E7318F0587CF9A2E0AFF74A6570E5753A3D"
E[2020-08-17|19:48:11.635] enterPrevote: ProposalBlock is invalid       module=consensus height=62 round=4 err="wrong Block.Header.AppHash.  Expected 1EAB96473578BEBA876CA9D204E64348C2DB2F3090753B53E7C8F880872C0A2A, got E5401BB87BF21409E6BE6BC740AE6E7318F0587CF9A2E0AFF74A6570E5753A3D"
E[2020-08-17|19:48:25.269] enterPrevote: ProposalBlock is invalid       module=consensus height=62 round=6 err="wrong Block.Header.AppHash.  Expected 1EAB96473578BEBA876CA9D204E64348C2DB2F3090753B53E7C8F880872C0A2A, got E5401BB87BF21409E6BE6BC740AE6E7318F0587CF9A2E0AFF74A6570E5753A3D"
E[2020-08-17|19:48:42.901] enterPrevote: ProposalBlock is invalid       module=consensus height=62 round=8 err="wrong Block.Header.AppHash.  Expected 1EAB96473578BEBA876CA9D204E64348C2DB2F3090753B53E7C8F880872C0A2A, got E5401BB87BF21409E6BE6BC740AE6E7318F0587CF9A2E0AFF74A6570E5753A3D"
```

**Comment by ChainCoderX** [comment]
ref  #348

**Comment by araskachoi** [comment]
I have noticed that node0 has the odd "round" and node1 has the even "round"
I also see that the apphashes that the nodes are expecting are swapped
node0: `Expected 1F482EDF235BF7EABA7D846C3957722A6EEE9607D3216DB41892DC9EFF65C67C, got 4E6D85124FD20EB9EFDDC03F2680D4EA508404EFAF65177FB1AA8EBAAFF0D47A"`
node1: `Expected 4E6D85124FD20EB9EFDDC03F2680D4EA508404EFAF65177FB1AA8EBAAFF0D47A, got 1F482EDF235BF7EABA7D846C3957722A6EEE9607D3216DB41892DC9EFF65C67C"`

<img width="1429" alt="node0_log" src="https://user-images.githubusercontent.com/13338103/90686199-d85c1b80-e21f-11ea-85da-bc8e2976f3d3.png">
<img width="1440" alt="node1_log" src="https://user-images.githubusercontent.com/13338103/90686220-dc883900-e21f-11ea-8209-e4de6c3b1160.png">

**Comment by fedekunze** [comment]
@araskachoi can you update the issue with the latest findings? 🙏
