### ISSUE TITLE
RPC endpoints for the local testnet isn't accessible on mac 

### ISSUE THREAD

**Issue by kanishkatn** [cosmos/ethermint#478]
__System info:__ 
Ethermint commit: Release v0.1.0
OS: macOS Catalina
Docker desktop: 2.3.0.4

__Steps to reproduce:__

1. Deploy a testnet with `make localnet-start`
2. Try to access the RPC endpoint of node0 with 
`curl -X POST --data '{"jsonrpc":"2.0","method":"eth_accounts","params":[],"id":1}' -H "Content-Type: application/json" <<CONTAINER_IP_ADDRESS>>:8545
`

__Expected behavior:__ A response from the RPC endpoint

__Actual behavior:__ Request timed out!

__Additional info:__ The issue seems to because of this: https://docs.docker.com/docker-for-mac/networking/#i-cannot-ping-my-containers

**Comment by J-Thompson12** [comment]
Docker on mac uses localhost. If you scroll to the top of the article you posted it explains you can start a container with port forwarding. I dont have a mac but try using localhost.

**Comment by kanishkatn** [comment]
@J-Thompson12  I'm getting this error for localhost
`curl: (52) Empty reply from server`

But, if I exec into the container and do the same request, it works!
