### ISSUE TITLE
websocket timeout

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ethermint#485]
Also wondering on the websockets—I think my request is getting timed out on a very simple eth_getLogs request.

Using `wscat` (similar to `ws`), I send a request for:

```
{"jsonrpc":"2.0","method":"eth_getLogs","params":[{"address": "0x439C697E0742A0DDB124A376EFD62a72A94aC35a", "fromBlock": "0x0"}],"id":1}
```

0x439C697E0742A0DDB124A376EFD62a72A94aC35a is just a simple contract that's emitted 4/5 events since the chain started.

I get back `{"error":{"code":-32000,"message":"internal"},"id":1,"jsonrpc":"2.0"}`, whereas a http request through curl gives me the correct logs.
I saw that there might've been some timeouts being applied (and reading the subscriptions-related code, is there also a reset applied every 5min for existing subscriptions?). Can I:

1. Configure this timeout?
2. Start `ethermintcli --rest-server --wsport` with a info/debug log level to get more information about the request and why they might be failing?

**Comment by noot** [comment]
possibly related to #524

**Comment by araskachoi** [comment]
Can you post the instructions for deploying the contract that you had deployed? I was able to get a non-error response from the ws but it was an empty response because the contract address does not exist.

**Comment by araskachoi** [comment]
Deploying a test contract
```
pragma solidity ^0.5.1;

contract Test {
    event Hello(uint256 indexed world);
    event TestEvent(uint256 indexed a, uint256 indexed b);

    uint256 myStorage;

    constructor() public {
        emit Hello(17);
    }

    function test(uint256 a, uint256 b) public {
        myStorage = a;
        emit TestEvent(a, b);
        }
    }
```

i was able to get this response back:
```
> {"jsonrpc":"2.0","method":"eth_getLogs","params":[{"address": "0xcfe7586ea2265110488a93fe70ab643cc8ce86e4", "fromBlock": "0x0"}],"id":1}
< {"id":1,"jsonrpc":"2.0","result":[{"address":"0xcfe7586ea2265110488a93fe70ab643cc8ce86e4","blockHash":"0x0000000000000000000000000000000000000000000000000000000000000000","blockNumber":"0x19c","data":"0x","logIndex":"0x0","removed":false,"topics":["0x775a94827b8fd9b519d36cd827093c664f93347070a554f65e4a6f56cd738898","0x0000000000000000000000000000000000000000000000000000000000000011"],"transactionHash":"0x7c3e537c37df848d65c8497928915a254cf4f0bc0500e197c8a94e981c565d74","transactionIndex":"0x0"}]}
```

**Comment by fedekunze** [comment]
It probably was the counter.sol contract. This is probably now fixed tho
