### ISSUE TITLE
Redeployments fail locally if the chain is not restarted

### ISSUE THREAD

**Issue by Clearwood** [cosmos/ethermint#490]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

Ethermint commit 4344dc10c72ed01986e5ab113ae0adc8f1ebe791

__Steps to reproduce:__

Run `truffle test` twice.

__Expected behavior:__ [What you expected to happen]

Deployments and tests running through normally. 

__Actual behavior:__ [What actually happened]

Internal error.
![image](https://user-images.githubusercontent.com/11144110/91853212-292d3480-ec62-11ea-890f-98987f766b9b.png)

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by noot** [comment]
hey @Clearwood, could you share the truffle contract and test you are using?

**Comment by araskachoi** [comment]
Closing, this issue has been resolved and cannot be reproduced.
