### ISSUE TITLE
Inconsistent JSON-RPC tests runs

### ISSUE THREAD

**Issue by fedekunze** [cosmos/ethermint#508]
From time to time the rpc tests CI workflow fails due to an unmarshaling issue with hex string. It'd be nice to fix it. Example failure:

```
=== RUN   TestEth_GetFilterChanges_Topics_XB
    rpc_test.go:693: 
        	Error Trace:	rpc_test.go:693
        	Error:      	Received unexpected error:
        	            	json: cannot unmarshal hex string of odd length into Go value of type hexutil.Bytes
        	Test:       	TestEth_GetFilterChanges_Topics_XB
``

**Comment by fedekunze** [comment]
I think we should be using `string` instead of `hexutil.Bytes` everywhere? cc: @noot

**Comment by noot** [comment]
@fedekunze yeah I think that would probably fix the issue

**Comment by fedekunze** [comment]
also related #418
