### ISSUE TITLE
failed to load state at height error

### ISSUE THREAD

**Issue by noot** [cosmos/ethermint#523]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. I am trying to reproduce this on a 1-node network but so far have only been able to do it on a 3-node network.
2. start 3 node network as per #513 
3. setup aragon truffle tests as per #516  then run`truffle test --network rpc`
4. usually after a few of the suites have been run, you are no longer able to query for a block because of this error
```
$ geth attach http://172.17.0.2:8545
Welcome to the Geth JavaScript console!

 modules: eth:1.0 net:1.0 personal:1.0 rpc:1.0 web3:1.0

> eth.getBlock(1)
Error: invalid request: failed to load state at height 27985; version does not exist (latest height: 90086)
```

it seems to be caused by different tests, so I'm not sure exactly what is causing this to happen, or why it is trying to query for a state that is lower than the latest

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
what's your node pruning configuration? the `ethermintd start` should be used with the `--pruning=nothing` flag

**Comment by noot** [comment]
@fedekunze I'm not currently starting the nodes with that, I'll try that and see how it goes!

**Comment by fedekunze** [comment]
we should probably add some docs about pruning configurations

**Comment by noot** [comment]
@fedekunze setting `--pruning=nothing` fixed it :D closing this for now
