### ISSUE TITLE
If a request other than "subscribe" is made to ethermintcli by websocket, the response is returned after "--read-timeout".

### ISSUE THREAD

**Issue by nueno4** [cosmos/ethermint#524]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

Ubuntu 20.04 64bit
Ethermint: v0.1.0

__Steps to reproduce:__

```console
$ git clone https://github.com/ChainSafe/ethermint.git
$ cd ethermint
$ git checkout -b v0.1.0 v0.1.0
$ make install

# console 1
$ ./init.sh

# console 2
$ ethermintcli rest-server --laddr "tcp://localhost:8545" --unlock-key mykey --chain-id 8 --read-timeout 20

# console 3
$ ws ws://localhost:8546
> {"jsonrpc":"2.0","id":1,"method":"eth_protocolVersion","params":[]}
< {"id":1,"jsonrpc":"2.0","result":"0x3f"}
```

__Expected behavior:__ [What you expected to happen]

The JSON-RPC "result" is output soon.

__Actual behavior:__ [What actually happened]

The JSON-RPC "result" is output after 20 seconds.

__Additional info:__ [Include gist of relevant config, logs, etc.]

* "eth_subscribe" method returns "result" soon.
* wireshark: "websocket request" --> "http request" --> "http response" --> **read timeout** --> "websocket response"

**Comment by araskachoi** [comment]
Unable to reproduce. I was able to get a response back in a timely manner.
https://github.com/ChainSafe/ethermint/issues/485#issuecomment-700272063

**Comment by hirokuma** [comment]
`eth_subscribe` return response soon, but other method(like `eth_protocolVersion`) is slow to respond.

```
{"id": 1, "method": "eth_subscribe", "params": ["newHeads", {}]}
```
