### ISSUE TITLE
Implement eth_getLogs

### ISSUE THREAD

**Issue by austinabell** [cosmos/ethermint#55]
* Will need to implement log reconstruction
  * See Ethereum Yellow Paper 4.3.1 for nitty gritty
  * Might be able to use Geth
* Note: logs are not stored, they typically have to be reconstructed from the txs and validated

**Comment by amerameen** [comment]
@dutterbutter Did #120 close this or is there more work to be done?

**Comment by dutterbutter** [comment]
More work still needs to be done. Such as having the block hash entered during log entry.

**Comment by dHonerkamp** [comment]
Hi, thanks for the great work on ethermint. We are very interested in testing some applications on it.

For this reason I was wondering if you have any details on when you expect the functionality around eth_getLogs, eth_newFilter etc. to land?
