### ISSUE TITLE
"Found a bug link doesn't work" on docs

### ISSUE THREAD

**Issue by okwme** [cosmos/ethermint#551]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

 * Go to [https://docs.ethermint.zone/basics/json_rpc.html](https://docs.ethermint.zone/basics/json_rpc.html)
 * Click "Found a bug link"

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by J-Thompson12** [comment]
The link anchor works in github and according to everything i saw the link anchor is setup properly. Im not sure why it wont work.

**Comment by fedekunze** [comment]
I think it's hardcoded on the template? cc: @lovincyrus

**Comment by okwme** [comment]
The link on the site took me to: https://github.com/ChainSafe/ethermint/edit/master/docs/basics/json_rpc.md when it should have taken me to: https://github.com/ChainSafe/ethermint/edit/development/docs/basics/json_rpc.md

**Comment by lovincyrus** [comment]
> I think it's hardcoded on the template? cc: @lovincyrus

Yeah, `master` branch is hardcoded on the template. 

https://github.com/cosmos/vuepress-theme-cosmos/blob/develop/layouts/GlobalLayout.vue#L365

**Comment by lovincyrus** [comment]
@fedekunze If you add `docsBranch: 'development',` to themeConfig in `.vuepress/config.js`, that should be able to fix it. The default branch of a vuepress theme is `master`.

Reference: https://vuepress.vuejs.org/theme/default-theme-config.html#git-repository-and-edit-links
