### ISSUE TITLE
Link anchor on rpc docs doenst work

### ISSUE THREAD

**Issue by J-Thompson12** [cosmos/ethermint#553]
![Screenshot 2020-09-23 142205](https://user-images.githubusercontent.com/37157877/94578312-d29d2100-0234-11eb-8913-7e822dfe5b72.png)

The rpc methods should be linked to the headers so a user can just click in the table and go to the information about that method but for some reason it doesnt work. It works if you are reading the docs in github but when its in docs website then it doesnt work.

__Expected behavior:__ [What you expected to happen]
clicking the method should take user to the method info.

__Actual behavior:__ [What actually happened]
changes the url but doesnt scroll

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by J-Thompson12** [comment]
I am going to close because its not a big deal with the sidebar allowing this functionality

**Comment by fedekunze** [comment]
this is because the sidebar doesn't use uppercases 

eg: [web3_clientVersion](https://docs.ethermint.zone/basics/json_rpc.html#web3_clientVersion) (table anchor) vs [web3-clientversion](https://docs.ethermint.zone/basics/json_rpc.html#web3-clientversion) (sidebar)
