### ISSUE TITLE
Modify RPC Server

### ISSUE THREAD

**Issue by ansermino** [cosmos/ethermint#58]
- Ensure its running on its own thread
- Take in handlers to retrieve data

**Comment by ansermino** [comment]
Presently HTTP requests are handled by the SDK client. The process works like this:

1. Route registration function is established 
    - eg. `"/ethermint/names"` => `func(w http.ResponseWriter, r *http.Request)`
2. Function is passed into SDK client ([`lcd.ServeCommand(cdc, registerRoutes)`](https://godoc.org/github.com/cosmos/cosmos-sdk/client/lcd#ServeCommand)),
3. SDK client starts HTTP service, passing requests to provided routes 

The Ethermint Web3 API presently works like this:
1. Handlers are defined to match the Web3 API interface (eg. `server/rpc/eth_api.go`). Note this interface is from `go-ethereum`.
2. To start the server the interface instances are passed to `rpc.StartHttpEndpoint()` (from `go-ethereum`) which takes care of the rest

These two approaches conflict. We cannot register a route in the SDK client since `go-ethereum` determines how requests are handled. If we remove the go-ethereum framing we need to implement our own RPC service and miss out on all their optimizations etc.

**Comment by austinabell** [comment]
Yeah, I believe the best bet is to have the two servers separate where the SDK REST server through a CLI command will act as a replacement to sending commands from the CLI and the web3 RPC API will be functionally the same as the Ethereum RPC API but send it's own RPC call to the daemon process. I believe as we discussed, it may be best to start the RPC server as it's own process, initiated by the CLI, but we can explore if it should be started with the daemon through a flag. 

Either way though I don't think there is a Cosmos SDK compliant way around not having to ultimately send an RPC request to the daemon to perform the state transition.
