### ISSUE TITLE
Bump cosmos-sdk version to v0.40.0-rc3

### ISSUE THREAD

**Issue by chengwenxi** [cosmos/ethermint#593]
@fedekunze Hi, I'm from IRISnet Dev team.

I saw some work about updating the cosmos-sdk version to v0.40.0-rc3 in the branch [stargate](https://github.com/cosmos/ethermint/tree/stargate).

Do you mind we join and work on it together to help complete it as soon as possilbe?

**Comment by fedekunze** [comment]
That would be very helpful! thanks @chengwenxi. Would you like to have a call or maybe @okwme can set up a shared channel for communications?

**Comment by chengwenxi** [comment]
> That would be very helpful! thanks @chengwenxi. Would you like to have a call or maybe @okwme can set up a shared channel for communications?

Help set up a shared channel? @okwme

**Comment by okwme** [comment]
gladly! look out for a DM via slack for an invite link to a new channel

**Comment by fedekunze** [comment]
this has been updated on the `stargate` branch
