### ISSUE TITLE
OVERSIZE genesis file with contracts exported

### ISSUE THREAD

**Issue by RevelationOfTuring** [cosmos/ethermint#624]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

operating system：macOS Catalina 10.15.6
go version：go1.15.2 darwin/amd64

I am amazing at the fact that the genesis file of ethermint is so large if some contracts deployed. Is there any solution to reduce the size?

NOTE: a simple ERC20 contract bytecode in genesis file exported reaches 5744 bytes.

Expected for the solution.

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by KamiD** [comment]
# Draft
hello @fedekunze , for this issue, how about the following solution:
* as we knew, byte code was saved as a static state db
* when someone want run a instance , EVM will load target byte code passthrough GetCode
* we can try refactor byte code management that make it separated from state db 
* when we need export genesis file, without byte code ,genesis file size will become less and readable
* the db of byte code should exported as a single db file independent existing(whatever the readable or size)

**Comment by zhongqiuwood** [comment]
Agree separating byte code data from genesis file
