### ISSUE TITLE
Implement IBC Protocol

### ISSUE THREAD

**Issue by grandbaiyi** [cosmos/ethermint#63]
In order to allow Inter blockchain(IBC) transfer it is required the integration of an IBC protocol such a Cosmos IBC. As we can see the Cosmos SDK is already integerated in ethermint, Is it already planning the work to implement Cosmos IBC protocol?

**Comment by austinabell** [comment]
IBC protocol is a module that will be implemented through cosmos-sdk, not through Ethermint. But yes, it is planned to be functional with the IBC protocol when it is available as the case with any other Cosmos SDK module.

Does this answer your question or would you like me to be more specific?
