### ISSUE TITLE
using a wrong nextRevisionID to revert a evm call

### ISSUE THREAD

**Issue by KamiD** [cosmos/ethermint#675]
## In EVM
* The following code segment means taking a snapshot, prepared for revert if `Call` function failed:
```go
snapshot := evm.StateDB.Snapshot()
```
https://github.com/ethereum/go-ethereum/blob/a425a47ddcb6078e2ae6ab062bb73f2c0939fd1d/core/vm/evm.go#L235

* revert to snapshot when `Call` function failed
```go
if err != nil {
		evm.StateDB.RevertToSnapshot(snapshot)
		if err != ErrExecutionReverted {
			gas = 0
		}
		// TODO: consider clearing up unused snapshots:
		//} else {
		//	evm.StateDB.DiscardSnapshot(snapshot)
	}
```
https://github.com/ethereum/go-ethereum/blob/a425a47ddcb6078e2ae6ab062bb73f2c0939fd1d/core/vm/evm.go#L280

## In Ethermint 
* this is our implementation of Snapshot, as we see, we are using code `csdb.nextRevisionID++` to generate a snapshot for caller
```go
// Snapshot returns an identifier for the current revision of the state.
func (csdb *CommitStateDB) Snapshot() int {
	id := csdb.nextRevisionID
	csdb.nextRevisionID++

	csdb.validRevisions = append(
		csdb.validRevisions,
		revision{
			id:           id,
			journalIndex: csdb.journal.length(),
		},
	)

	return id
}
```

The problem is when we restart a node with snapshot, the `csdb.nxtRevisionID` will set to zero, it's difference with other running node, that means we are using a wrong `csdb.nextRevisionID` to revert a evm call
```

**Comment by fedekunze** [comment]
nice catch, this is indeed a bug 👍

**Comment by KamiD** [comment]
hi @fedekunze , about this issue, I think maybe this is not a bug because every block will reset the `validRevisions` by calling `clearJournalAndRefund` in `Reset`, that means revision just focus on one block executing, if nextRevisionID can pointing a valid Revision correctly,  it's no matter what the `nextRevisionID` is
am i right ?

**Comment by KamiD** [comment]
I think this issue can be closed
