### ISSUE TITLE
It returns error when "--chain-id" was set empty during "ethermintd init"

### ISSUE THREAD

**Issue by RevelationOfTuring** [cosmos/ethermint#681]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
It says that "genesis file chain-id, if left blank will be randomly created" in `ethermintd init -h`
![image](https://user-images.githubusercontent.com/46394603/103349974-78cd2100-4ad9-11eb-93d8-214b876f492e.png)

commit：9659b81

__Steps to reproduce:__

It set empty for `--chaind-id` :
```shell
 $ ethermintd init alice
```

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]
And it returns an error:
```
ERROR: invalid chain-id format: 
```
__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by RevelationOfTuring** [comment]
经测试ethermint也存在这个问题，已向社区发issue：
https://github.com/cosmos/ethermint/issues/681

**Comment by fedekunze** [comment]
ah yeah the help message is from the Cosmos SDK which doesn't enforce a chain-id format. We can update the help message to require the chain-id and also the error message to be more descriptive

**Comment by helder-moreira** [comment]
@fedekunze isn't it possible to make it generate a compatible chain-id by default?

**Comment by fedekunze** [comment]
you can but it needs to have the format `<chain_name>-<chain_id>`

**Comment by helder-moreira** [comment]
It would basically require replacing [this](https://github.com/cosmos/ethermint/blob/development/cmd/ethermintd/main.go#L69) with a copy of the [InitCmd](https://github.com/cosmos/cosmos-sdk/blob/master/x/genutil/client/cli/init.go#L67-L152) with [this line](https://github.com/cosmos/cosmos-sdk/blob/master/x/genutil/client/cli/init.go#L84) adapted to the right format. Am I right? Would you welcome a PR for that?

EDIT: or maybe just another wrapper on the command to generate the chain-id.
