### ISSUE TITLE
Document the current chain-id rule

### ISSUE THREAD

**Issue by liuxingxing1** [cosmos/ethermint#682]
you now METAMASK chain-id must a decimal or '0x'-prefixed hexadecimal number. However, the ethermint chain-ID format cannot meet the requirements of METAMASK.

**Comment by fedekunze** [comment]
Hi @liuxingxing1. The chain-id needs to have the following name to satisfy both IBC and Ethermint requirements:

`<chain_name>-<number>`: eg `ethermint-2`

Note that if you set the number to `1`, most of Ethereum tooling will assume that you are interacting with Ethereum mainnet, so I'd advise not using that one.

We will add a document that documents this better 👍
