### ISSUE TITLE
Mismatch Block Hash in RPC Response

### ISSUE THREAD

**Issue by ghost** [cosmos/ethermint#721]
__System info:__ 

In RPC `eth.getBlock` Response, the Block Hash is generated by `header.Hash()` which mismatch the `header.LastBlockID.Hash`.

For example, `Block[N+1] Parent Hash` != `Block[N] Block Hash` due to the `Block[N].header.Hash() != Block[N+1]. header.LastBlockID.Hash`.

__Steps to reproduce:__

Simply start the chain and observe the `parentHash` field of any Block Height > 1 and the previous Block in RPC `eth.getBlock` Response.

Some of the Block Hash may not equal the next Block's Parent Hash.

__Expected behavior:__ Block[N] Hash = Block[N+1] Parent Hash

__Actual behavior:__ Block[N] Hash != Block[N+1] Parent Hash

__Additional info:__ 

We may use back the BlockID information from the Tendermint `ResultBlock` Response to reproduce a correct Block Hash.

A simple modification can reference to [Fix Web3 Block Hash](https://github.com/redbud-hk/ethermint/pull/5/files)

**Comment by fedekunze** [comment]
closed via #755
