### ISSUE TITLE
Contract migration by truffle not working

### ISSUE THREAD

**Issue by freddyli7** [cosmos/ethermint#729]
__System info: __
macOS 11.1
ethermint: 0.3.0-50-g3767729
go: 1.15.6 darwin/amd64
Truffle: v5.1.62 (core: 5.1.62)
Solidity: v0.5.16 (solc-js)
Node: v15.6.0
Web3.js: v1.2.9
contract: ^0.5.11
ganache: v2.5.4 with hardfork Petersburg

__Steps to reproduce:__

1. follow the truffle doc to setup a brand new truffle project: https://github.com/cosmos/ethermint/blob/development/docs/guides/truffle.md
2. start ethermint local node with default `init.sh`
3. run `truffle migrate --network development` after `compile`

__Expected behavior:__ 
1. Migrations dry-run (simulation) runs without error: `Deploying Migrations` and  `Deploying Counter`
2. Actual deployment runs without error: `Deploying Migrations` and  `Deploying Counter`

__Actual behavior:__
1. Migrations dry-run (simulation) runs without error: `Deploying Migrations` and  `Deploying Counter`
2. Actual deployment got stuck at `Deploying Migrations` and fail after few mins.

__Additional info:__ 

truffle migration error:
![Screen Shot 2021-01-19 at 11.03.38.png](https://images.zenhubusercontent.com/5ffca43d3b604155bec1f567/7ebd26e6-ee8f-4db8-bc68-324d76ee5cd2)

ethermint node log: 
```
I[2021-01-19|11:29:38.353] Added good transaction                       module=mempool tx=3BDD60F812C981D4B5D94AB58AB8104530E67C187859E28DB035C2E85B1ED575 res="&{CheckTx:log:\"[]\" gas_wanted:6721975 }" height=628 total=1
I[2021-01-19|11:29:42.228] Executed block                               module=state height=629 validTxs=1 invalidTxs=0
I[2021-01-19|11:29:42.247] Committed state                              module=state height=629 txs=1 appHash=3791156F36B1B0D26F3B3F8CCE38B3F550644D6CC23F1F0777226AC3AC330BED
```

node log doesn't show any error, and node didn't crash, node log only shows `Added good transaction` message like above when `truffle migration` cmd starts running.  

the migration works on ganache with local ethereum

**Comment by freddyli7** [comment]
tested with `chainID=ethermint-9999`(different from any reserved ethereum chainID), still the same behavior.

**Comment by araskachoi** [comment]
Still looking into what is going on here. may be a truffle issue. 

@freddyli7, were you able to rollback and see if there were any releases that passed the truffle migrate?
