### ISSUE TITLE
Verify RPC Value Format Match Spec

### ISSUE THREAD

**Issue by ansermino** [cosmos/ethermint#73]
There are specific guidelines for how values are returned: https://github.com/ethereum/wiki/wiki/JSON-RPC#hex-value-encoding

We should test against this to ensure capability with existing web3 clients.

**Comment by austinabell** [comment]
Closing issue because spec is inconsistent and not updated for changes made in clients. More important issue to track is dev tooling compatibility, which is an ongoing process
