### ISSUE TITLE
Incorrect calculate blockchain hash in evm rpc module

### ISSUE THREAD

**Issue by louisliu2048** [cosmos/ethermint#751]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
In app/rpc/namespace directory, the method to get blockHash is:
`blockHash := common.BytesToHash(block.Block.Header.Hash())`
but in tendermint, the method to get blockHash is: 
tendermint/state/execution.go:284
```
	// Begin block
	var err error
	abciResponses.BeginBlock, err = proxyAppConn.BeginBlockSync(abci.RequestBeginBlock{
		Hash:                block.Hash(),
		Header:              types.TM2PB.Header(&block.Header),
		LastCommitInfo:      commitInfo,
		ByzantineValidators: byzVals,
	})
```
`Header.Hash()` will not include `LastCommit *Commit ` info!
The current method will introduce https://github.com/cosmos/ethermint/issues/721 error.

__Steps to reproduce:__

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by fedekunze** [comment]
closed via #755
