### ISSUE TITLE
Stargate Solidity Tests

### ISSUE THREAD

**Issue by freddyli7** [cosmos/ethermint#765]
we need to update `run-solidity-tests.sh` and `init-node.sh` under `/tests-solidity` for all related scripts

Also need to fix the `ethermintd` binary.

**Comment by araskachoi** [comment]
Acceptance Criteria:
Solidity tests pass

**Comment by freddyli7** [comment]
Updated test results:
   ```
    1. test-contract => 🟢
    2. test-solidity => 🟡
```

For `test-solidity`, the issue is all the fields for the `MsgEthereumTxResponse` are put into the `contractAddress` field, so that the actual `contractAddress` is a long string instead of a 42 chars valid address, it will cause truffle parsing issue,  also `data.Ret` has no contract call response. The assumption is in the protobuf encoding/decoding
