### ISSUE TITLE
Stargate Simulation Tests

### ISSUE THREAD

**Issue by freddyli7** [cosmos/ethermint#766]
1. `test-sim-nondeterminism` => Pass
2. `test-sim-custom-genesis-fast` => Failed

    Error: pubKey does not match signer address eth1fx3j6kzwwhfajagemcnvv6jrkvy7h2nc9wexaw with signer index: 0
    `eth1fx3j6kzwwhfajagemcnvv6jrkvy7h2nc9wexaw` is the test account generated with `keys` cmd

3. `test-sim-import-export` => Failed
   Error: UnmarshalJSON cannot decode empty bytes
  
4. `test-sim-after-import` => Failed
  Error: UnmarshalJSON cannot decode empty bytes
  
5. `test-sim-custom-genesis-multi-seed` => Failed
  Error: UnmarshalJSON cannot decode empty bytes

6. `test-sim-multi-seed-long` => Failed
   Error: UnmarshalJSON cannot decode empty bytes

7. `test-sim-multi-seed-short` => Failed
   Error: UnmarshalJSON cannot decode empty bytes

Note: `UnmarshalJSON cannot decode empty bytes` is the same error when crisist module load in an incorrect order.

**Comment by araskachoi** [comment]
Acceptance Criteria:
Simulation tests must pass on the CI

**Comment by freddyli7** [comment]
Updated test result:

	1. test-sim-nondeterminism => 🟢
	2. test-sim-custom-genesis-fast => 🟡
	3. test-sim-import-export => 🟡
	4. test-sim-after-import => 🟡
	5. test-sim-custom-genesis-multi-seed => 🟡
	6. test-sim-multi-seed-long => 🟢
	7. test-sim-multi-seed-short => 🟢

2,3,4 and 5 have the same error: `pubkey does not match signer addres xxxx with signer index: 0` 
after force it to run with `simulation=true`, issue resolved and all tests pass. 

One fix on the cosmos-sdk side: 
need to assign `ed25519` prikey to ConsKey at `cosmos-sdk/simapp/state.go` ->  `func AppStateFromGenesisFileFn`

**Comment by freddyli7** [comment]
We disabled the sim tests for now
