### ISSUE TITLE
Failed to call rpc interface eth_getLogs

### ISSUE THREAD

**Issue by KamiD** [cosmos/ethermint#771]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]

__Steps to reproduce:__

1. [First Step]
* deploy and run a local node
2. [Second Step]
* deploy a smart contract demo like follow:
```solidity
// SPDX-License-Identifier: GPL-3.0

pragma solidity >=0.7.0 <0.8.0;

/**
 * @title Storage
 * @dev Store & retrieve value in a variable
 */
contract Storage {

    uint256 number;
    event Test(address to);

    /**
     * @dev Store value in variable
     * @param num value to store
     */
    function store(uint256 num) public {
        number = num;
        emit Test(msg.sender);
    }

    /**
     * @dev Return value 
     * @return value of 'number'
     */
    function retrieve() public view returns (uint256){
        return number;
    }
}
```
3. [and so on...]
* call `store` to test event(log)

__Expected behavior:__ [What you expected to happen]
* should get the log by using `eth_getLogs`

__Actual behavior:__ [What actually happened]
* nothing return

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by araskachoi** [comment]
@kamiD what are the parameters you are passing to `eth_getLogs`?
