### ISSUE TITLE
wrong precision in calculation of gas fee during call AnteHandler

### ISSUE THREAD

**Issue by KamiD** [cosmos/ethermint#799]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
Code: 177574aafa34683ccd1823cdb8ca5642f271e48d

__Steps to reproduce:__

https://github.com/cosmos/ethermint/blob/177574aafa34683ccd1823cdb8ca5642f271e48d/app/ante/eth.go#L102
call `NewDecCoin ` will increment precision to 18, it means if you call it like:
```go
fee := NewDecCoin("eth",1)
```
The `fee` will become to 1000000000000000000, that's a wrong precision calculation

1. [First Step]
2. [Second Step]
3. [and so on...]

__Expected behavior:__ [What you expected to happen]

__Actual behavior:__ [What actually happened]

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by araskachoi** [comment]
That looks correct here no? the proper precision should be 1x10^18 and that's what it looks like it's doing here. can you provide more explanation here? otherwise, this looks like a non-issue

**Comment by KamiD** [comment]
> That looks correct here no? the proper precision should be 1x10^18 and that's what it looks like it's doing here. can you provide more explanation here? otherwise, this looks like a non-issue

for example: if I set gas price to 1 GWEI in metamask or any other wallets of ethereum, the member `Price` of MsgEthereumTx will be set to 1000000000, that means `Price` has already increase to 1 x 10^9, it equal with `0.000000009 eth`, if here increase precision with 18 again, it will be 1 x 1000000000^18, that's a wrong precision number
