### ISSUE TITLE
RPC eth_sendTransaction does not work as expected when not setting GasPrice & Gas manually

### ISSUE THREAD

**Issue by banishee** [cosmos/ethermint#802]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
* branch `dev`

__Steps to reproduce:__

1. Use `eth_SendTransaction` api to deploy a contract, without `GasPrice` and `Gas` parameters

2. This transaction will fail beacause of a lack of `fee`
```shell
{Code:-32000, Message:"insufficient fee: insufficient fee, got: \"0.000000000001317060okt\" required: 0.000065853000000000", Data:interface {}(nil)}
```

__Expected behavior:__ [What you expected to happen]
* the transaction without `GasPrice` and `Gas` manual parameters should be set with appropriate value automatically

__Actual behavior:__ [What actually happened]
* the transaction just fails with an error in https://github.com/cosmos/ethermint/blob/fae8147352e65b86f0755a081f3b59b1e25d48bf/rpc/namespaces/eth/api.go#L1049

__Additional info:__ [Include gist of relevant config, logs, etc.]
* Here is the way of generating args. When `GasPrice` and `Gas` are nil, the program will use the default value as `GasPrice`. But it won't go through in `api.EstimateGas(callArgs)`, when the value of `ethermint.DefaultGasPrice` is less than the value of `minimum-gas-prices` in a validator
```golang
func (api *PublicEthereumAPI) generateFromArgs(args rpctypes.SendTxArgs) (*evmtypes.MsgEthereumTx, error) {
	...

	if args.GasPrice == nil {
		// Set default gas price
		// TODO: Change to min gas price from context once available through server/daemon
		gasPrice = big.NewInt(ethermint.DefaultGasPrice)
	}
	...

       if args.Gas == nil {
		callArgs := rpctypes.CallArgs{
			From:     &args.From,
			To:       args.To,
			Gas:      args.Gas,
			GasPrice: args.GasPrice,
			Value:    args.Value,
			Data:     args.Data,
		}
               
		gl, err := api.EstimateGas(callArgs)
		...
	} else {
		...
	}
        ...
	return &msg, nil
}
```

**Comment by freddyli7** [comment]
The issue have been fixed in previous version. The current version `0.4.1-7-g20f9a72` binary works well with both`gas` and/or `gasPrice` provided or not provided.
