### ISSUE TITLE
Metamask Balance not correct

### ISSUE THREAD

**Issue by veqtor** [cosmos/ethermint#822]
__System info:__ 
Ethermint 0.4.0
OS: Mac OS Catalina (10.15.6 (19G2021))

__Steps to reproduce:__

1. Install fresh and build
2. Start using ./init.sh
3. Run ethermintcli for json-rpc
4. Get private key from ethermintcli
5. Add private key to Metamask
6. Connect Metamask to local json-rpc

__Expected behavior:__ 
Account should show up as having 99 PROTON

__Actual behavior:__
Metamask doesn't update account, preventing transfers (due to a guard), making it impossible to test and run using Remix etc

**Comment by Khaos-Labs** [comment]
Can solve this problem as soon as possible?

**Comment by temaniarpit27** [comment]
Hi guys,
I am facing the same issue.
Let me know any resolutions for it and any ETA for this fix.
