### ISSUE TITLE
The txhash published from PendingTransactionsSubscription websocket are all already committed in the block

### ISSUE THREAD

**Issue by banishee** [cosmos/ethermint#833]
__System info:__ [Include Ethermint commit, operating system name, and other relevant details]
the `development` branch

__Steps to reproduce:__

1. [First Step]
start a websocket client, then send transcations on a local node
```shell
$ wscat -c ws://127.0.0.1:8546
> {"id": 1, "method": "eth_subscribe", "params": ["newPendingTransactions"]}
< {"jsonrpc":"2.0","result":"0x9789a5feaffc47d2669be4b79fd03e21","id":1}

< {"jsonrpc":"2.0","method":"eth_subscription","params":{"subscription":"0x9789a5feaffc47d2669be4b79fd03e21","result":"0x492660be45ab6cbb88c416620b38b77c874a0321d5f7db8c035ee42179251d56"}}
```
2. [Second Step]
However, I noticed that every txhash that the ws-client received is already being committed in the block.

__Expected behavior:__ [What you expected to happen]
The `eth_subscribe` method with params `newPendingTransactions` should return the list of tx from mempool, not committed block.

__Actual behavior:__ [What actually happened]
 In `tendermint@v0.39.3` , https://github.com/tendermint/tendermint/blob/94ea3c83a8cfa63c8cd7502dd581b552e81dbf23/state/execution.go#L470
the `eventBus` only iterates the `block.Data.Txs`, then publishes them

__Additional info:__ [Include gist of relevant config, logs, etc.]

**Comment by banishee** [comment]
@araskachoi

**Comment by freddyli7** [comment]
can you please try to start a node with `pending` mode
