### ISSUE TITLE
Failed to subscribe to init.sh

### ISSUE THREAD

**Issue by sdelvalle57** [cosmos/ethermint#835]
__System info:__ Linux Ubuntu 20.04

__Steps to reproduce:__

1. Cloned repo `git clone https://github.com/cosmos/ethermint.git`
2.  Run `ethermintcli rest-server --laddr "tcp://localhost:8545" --unlock-key mykey --chain-id ethermint-982 --trace`

__Expected behavior:Attach to node
__Actual behavior:
````
panic: failed to subscribe pending txs: client is not running. Use .Start() method to start

goroutine 32 [running]:
github.com/cosmos/ethermint/rpc/namespaces/eth/filters.(*EventSystem).eventLoop(0xc0000d3900)
        /home/santiago/projects/ethermint/rpc/namespaces/eth/filters/filter_system.go:297 +0xe65
created by github.com/cosmos/ethermint/rpc/namespaces/eth/filters.NewEventSystem
        /home/santiago/projects/ethermint/rpc/namespaces/eth/filters/filter_system.go:88 +0x24d
````

**Comment by Khaos-Labs** [comment]
The same mistake happened 。

**Comment by araskachoi** [comment]
Hello, I am unable to reproduce this error. do you think you can update the ticket with some additional information regarding your environment and reproduction steps please? thank you

**Comment by Khaos-Labs** [comment]
Issue resolved：
ethermintcli rest-server --laddr "tcp://localhost:8545" --node "tcp://127.0.0.1:26657" --unlock-key mykey --chain-id 1 --trace --rpc-api "web3,eth,net"

maybe ：（dev branch code）
rpc/apis.go : selectedApis []string can‘t empty。
func GetAPIs(clientCtx context.CLIContext, selectedApis []string, keys ...ethsecp256k1.PrivKey) []rpc.API {
	nonceLock := new(rpctypes.AddrLocker)
	backend := backend.New(clientCtx)
	ethAPI := eth.NewAPI(clientCtx, backend, nonceLock, keys...)

	var apis []rpc.API

	for _, api := range selectedApis {
		switch api {
		case Web3Namespace:
			apis = append(apis,
				rpc.API{
					Namespace: Web3Namespace,
					Version:   apiVersion,
					Service:   web3.NewAPI(),
					Public:    true,
				},
			)
		case EthNamespace:
			apis = append(apis,
				rpc.API{
					Namespace: EthNamespace,
					Version:   apiVersion,
					Service:   ethAPI,
					Public:    true,
				},
			)
			apis = append(apis,
				rpc.API{
					Namespace: EthNamespace,
					Version:   apiVersion,
					Service:   filters.NewAPI(clientCtx, backend),
					Public:    true,
				},
			)
		case PersonalNamespace:
			apis = append(apis,
				rpc.API{
					Namespace: PersonalNamespace,
					Version:   apiVersion,
					Service:   personal.NewAPI(ethAPI),
					Public:    false,
				},
			)
		case NetNamespace:
			apis = append(apis,
				rpc.API{
					Namespace: NetNamespace,
					Version:   apiVersion,
					Service:   net.NewAPI(clientCtx),
					Public:    true,
				},
			)
		}
	}

	return apis
}

**Comment by araskachoi** [comment]
thank you for your response! taking a closer look, I have identified the error! a PR has been created to address this issue
