### ISSUE TITLE
personal_newAccount  error - method handler crashed 

### ISSUE THREAD

**Issue by steventranjs** [cosmos/ethermint#852]
__System info:__ [development]

__Steps to reproduce:__

1. Start localnet stack
```
make localnet-start
```
2. Enter `ethermintdnode0` container and create a new account
```
docker exec -it ethermintdnode0 bash
curl -X POST --data '{"jsonrpc":"2.0","method":"personal_newAccount","params":["This is the passphrase"],"id":1337}' -H "Content-Type: application/json" http://localhost:8545
```

__Expected behavior:__ New account successfully created

__Actual behavior:__ curl crashed with error: `{"jsonrpc":"2.0","id":1337,"error":{"code":-32000,"message":"method handler crashed"}}`

**Comment by freddyli7** [comment]
this issue has been fixed in `stargate` upgrade
