### ISSUE TITLE
eth_getLogs fail after some time

### ISSUE THREAD

**Issue by AlibekKarimov** [cosmos/ethermint#855]
__System info:__ [ethermint version: 0.4.1-6-g75fb3cc, OS: Ubuntu 20.04.2 LTS]

__Steps to reproduce:__

1. run ethermint from clear
2. deploy sample contract 
3. send transactions
3. querying contract transactions by file (eth_getLogs)

__Expected behavior:__ Get array of transactions by filter

__Actual behavior:__ request failed
```
"Error: processing response error (body=\"{\\\"jsonrpc\\\":\\\"2.0\\\",\\\"id\\\":98,\\\"error\\\":
{\\\"code\\\":-32000,\\\"message\\\":\\\"ConsensusParams: RPC error -32603 - Internal error: could not find consensus 
params for height #5807\\\"}}\\n\", error={\"code\":-32000}, requestBody=\"
{\\\"method\\\":\\\"eth_getLogs\\\",\\\"params\\\":
[{\\\"fromBlock\\\":\\\"0x0\\\",\\\"toBlock\\\":\\\"latest\\\",\\\"address\\\":\\\"0x4ec7759b35e3a62def100d3a5f5251f0d
bbea783\\\",\\\"topics\\\":
[\\\"0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef\\\"]}],\\\"id\\\":98,\\\"jsonrpc\\\":\\\"2.0\\
\"}\", requestMethod=\"POST\", url=\"http://127.0.0.1:8545\", code=SERVER_ERROR, version=web/5.0.13)
```

```
requestBody: '{"method":"eth_getLogs","params":
[{"fromBlock":"0x0","toBlock":"latest","address":"0x4ec7759b35e3a62def100d3a5f5251f0dbbea783","topics":
["0xddf252ad1be2c89b69c2b068fc378daa952ba7f163c4a11628f55a4df523b3ef"]}],"id":98,"jsonrpc":"2.0"}'
```
__Additional info:__on clear ethermint installation no issue, but after some time if u try getLogs the exception starts to throw

**Comment by AlibekKarimov** [comment]
[getLogsSample.zip](https://github.com/cosmos/ethermint/files/6333904/getLogsSample.zip)

this is sample application which emit event in contract and try get logs every minute. If you run it from clear installation of ethermint it will work some time until fail, my failed on block count 436 
<img width="1450" alt="Screen Shot 2021-04-19 at 12 32 36" src="https://user-images.githubusercontent.com/82081266/115194796-c2d12580-a10f-11eb-8309-4f5cc318920f.png">

then if start app again it fail after first get logs

**Comment by freddyli7** [comment]
hey @AlibekKarimov, I followed the steps above but wasn't able to reproduce the issue, the `eth_getLogs` endpoint works fine for me. I did wait for a long time to see if it still works. Do you recall that if you did something else after query logs for the first time which might cause this issue? by the way, the version I used is `0.4.1-7-g20f9a72` which is slightly newer than yours, can you please try it again. Let us know if it works for you.

**Comment by AlibekKarimov** [comment]
Thank you @freddyli7, I have updated to 0.4.1-7-g20f9a72 version and it fail again. Did you try my sample application for reproduce issue attached to previous comment? 
Do you need any additional info from my ethermint instance?

**Comment by ghost** [comment]
> [getLogsSample.zip](https://github.com/cosmos/ethermint/files/6333904/getLogsSample.zip)
> 
> this is sample application which emit event in contract and try get logs every minute. If you run it from clear installation of ethermint it will work some time until fail, my failed on block count 436
> <img alt="Screen Shot 2021-04-19 at 12 32 36" width="1450" src="https://user-images.githubusercontent.com/82081266/115194796-c2d12580-a10f-11eb-8309-4f5cc318920f.png">
> 
> then if start app again it fail after first get logs

I experience this the same, every RPC call will happen,
since I set the consensus block time to 1,
I can reproduce the behavior no matter I called `eth.getBlock(..)` or any other RPC.

I observed the behavior will happen when the consensus is finalizing (just before the block is confirmed).
