### ISSUE TITLE
are there project support ABI interfaces for every cosmos module  interface cmd ?

### ISSUE THREAD

**Issue by ChainCoderX** [cosmos/ethermint#870]
are there project support ABI interfaces for every cosmos module  interface cmd ?

**Comment by freddyli7** [comment]
hi @wade-liwei , not sure what you meant by `ABI interfaces for every cosmos module`. In ethermint, all the `evm` module RPC endpoints that interact with contract would only consume `contract address` and `contract data`, the `ABI` is not handled on ethermint protocol side, it's supposed to be handled on upper layer such as `web3js`. Let us know if this answers you question.

**Comment by ChainCoderX** [comment]
requirement:

1. define ABI interface;
2. in evm module decode the ABI  with the specific contract address, then call the cosmos module interface, like staking、distribution 
3. on the frontend, call the evm rawTx interface with web3js.

**Comment by freddyli7** [comment]
hi @wade-liwei, for cosmos modules such as `staking`, you can refer to [cosmjs](https://github.com/cosmos/cosmjs), for evm module, ethermint has the RPC compatibility with `web3js`, please note that we are working on adding new RPC endpoints, here is the [RPC endpoint doc](https://docs.ethermint.zone/basics/json_rpc.html)

**Comment by ChainCoderX** [comment]
got it, think you.
