### ISSUE TITLE
-bash: ethermintd: command not found

### ISSUE THREAD

**Issue by ghost** [cosmos/ethermint#873]
After cloning and installing ethermint I cannot check if the binaries have been installed using `ethermintd -h` I get command not found, would appreciate any guidance.

**Comment by ghost** [comment]
I updated my version of go lang and deleted my previous version

**Comment by araskachoi** [comment]
Hello @spindriftur,
looks like this is a go env issue. Please make sure that your GOPATH and GOBIN env vars are set properly. If you have built the files locally using `make install`, the `./cmd/` directory. If you have used `make docker-build`, it should be saved in the `build` directory.
Please let me know if this resolves your issue!

**Comment by spindriftur** [comment]
So the PATH env variables should be saved in the `./cmd/` directory? Sorry I don't understand

**Comment by ghost** [comment]
How do I make sure my GOPATH and GOBIN env vars are set properly?

**Comment by ghost** [comment]
I do not have `ethermintd` in my GOPATH after checking using `go env` to view everything, any idea how to add it? Thank you

**Comment by ghost** [comment]
It is working for some reason now after doing nothing, thanks anyways
