### ISSUE TITLE
Implement block tags

### ISSUE THREAD

**Issue by ansermino** [cosmos/ethermint#93]
Presently RPC calls are only supported with block numbers (height) and not tags (eg. 'latest', 'pending'). 
The parameter for calls that have a tag/height parameter is currently [`BlockNumber`](https://godoc.org/github.com/ethereum/go-ethereum/rpc#BlockNumber). This may not be compatible with our implementation as the unmarshalling handles block tags but there is no indication of how values are determined (eg. how it knows the latest block) 

Possible tags (https://github.com/ethereum/wiki/wiki/JSON-RPC#the-default-block-parameter):
```
HEX String - an integer block number
String "earliest" for the earliest/genesis block
String "latest" - for the latest mined block
String "pending" - for the pending state/transactions

```

**Comment by austinabell** [comment]
Note: querying tendermint block at height 0 is the equivalent of "latest", which is the default value. We also won't be able to query the pending block yet until the unconfirmed tx tm query is built out.
Not sure how we query the genesis/earliest block if 0 translates to "latest" though
