### ISSUE TITLE
New Transaction on chain

### ISSUE THREAD

**Issue by blockchain-app12** [cosmos/ethermint#97]
__Proposal:__ New transaction after starting emintd.

__Current behavior:__ There is a feature to add tx at genesis with gentx command. However there are no options for creating new transaction after genesis

__Desired behavior:__ Feature to have a new transaction after genesis

__Use case:__ Having a new feature will let mimic ethereum behavior in a better way

**Comment by austinabell** [comment]
There is a command, with no state transition, but #96 will allow this, just waiting on a few details to be resolved. RPC calls regarding txs will come in soon as well.

**Comment by austinabell** [comment]
Resolved with #96, can send transactions through CLI. web3 tx endpoints will be coming in throughout next couple days
