### ISSUE TITLE
emintcli query ethermint block-number xxx command results in "could not resolve: ABCIQuery: response error: RPC error -32603 - Internal error: runtime error: invalid memory address or nil pointer dereference"

### ISSUE THREAD

**Issue by blockchain-app12** [cosmos/ethermint#98]
__System info:__ Ubuntu 16.04. tendermint: 0.32.2 abci: 0.16.1 blockprotocol: 10 p2pprotocol: 7

__Steps to reproduce:__

1. Terminal 1 : emintd start. emint daemon is running.
2. Terminal 2 : emintcli query ethermint block-number xxx results in "could not resolve: ABCIQuery: response error: RPC error -32603 - Internal error: runtime error: invalid memory address or nil pointer dereference"

__Expected behavior:__ For the query command to fetch details of specific block-number

__Actual behavior:__ results in "could not resolve: ABCIQuery: response error: RPC error -32603 - Internal error: runtime error: invalid memory address or nil pointer dereference"

**Comment by austinabell** [comment]
Fix for that will be coming in, all of this is WIP and shouldn't be tested as a functional chain yet. Will be usable when #96 or #94 comes in. This query actually doesn't have a parameter by the way, just queries the current block number to match eth_getBlockNumber rpc call.

**Comment by austinabell** [comment]
Resolved with #96
